// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controlDialogo.proto

package com.bbva.business.gateway.controldialogo;

public final class ControlDialogo {
  private ControlDialogo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_b_gateway_v1_Iso20022ControlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_b_gateway_v1_Iso20022ControlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_b_gateway_v1_Iso20022ControlResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_b_gateway_v1_Iso20022ControlResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024controlDialogo.proto\022\014b.gateway.v1\"\320\001\n" +
      "\026Iso20022ControlRequest\022\027\n\017messageFuncti" +
      "on\030\001 \001(\t\022\016\n\006header\030\002 \001(\t\022\034\n\024transmission" +
      "DateTime\030\003 \001(\t\022\036\n\026systemTraceAuditNumber" +
      "\030\004 \001(\t\022\026\n\016settlementDate\030\005 \001(\t\022\024\n\014additi" +
      "onalId\030\006 \001(\t\022!\n\031networkManagementInfoCod" +
      "e\030\007 \001(\t\"\341\001\n\027Iso20022ControlResponse\022\027\n\017m" +
      "essageFunction\030\001 \001(\t\022\016\n\006header\030\002 \001(\t\022\034\n\024" +
      "transmissionDateTime\030\003 \001(\t\022\036\n\026systemTrac" +
      "eAuditNumber\030\004 \001(\t\022\026\n\016settlementDate\030\005 \001" +
      "(\t\022\024\n\014additionalId\030\006 \001(\t\022!\n\031networkManag" +
      "ementInfoCode\030\007 \001(\t\022\016\n\006result\030\010 \001(\t2\206\001\n\025" +
      "ControlDialogoService\022m\n\034ControlDialogoP" +
      "rocessMessage\022$.b.gateway.v1.Iso20022Con" +
      "trolRequest\032%.b.gateway.v1.Iso20022Contr" +
      "olResponse\"\000B,\n(com.bbva.business.gatewa" +
      "y.controldialogoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_b_gateway_v1_Iso20022ControlRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_b_gateway_v1_Iso20022ControlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_b_gateway_v1_Iso20022ControlRequest_descriptor,
        new java.lang.String[] { "MessageFunction", "Header", "TransmissionDateTime", "SystemTraceAuditNumber", "SettlementDate", "AdditionalId", "NetworkManagementInfoCode", });
    internal_static_b_gateway_v1_Iso20022ControlResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_b_gateway_v1_Iso20022ControlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_b_gateway_v1_Iso20022ControlResponse_descriptor,
        new java.lang.String[] { "MessageFunction", "Header", "TransmissionDateTime", "SystemTraceAuditNumber", "SettlementDate", "AdditionalId", "NetworkManagementInfoCode", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
