// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controlDialogo.proto

package com.bbva.business.gateway.controldialogo;

/**
 * Protobuf type {@code b.gateway.v1.Iso20022ControlResponse}
 */
public  final class Iso20022ControlResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:b.gateway.v1.Iso20022ControlResponse)
    Iso20022ControlResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Iso20022ControlResponse.newBuilder() to construct.
  private Iso20022ControlResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Iso20022ControlResponse() {
    messageFunction_ = "";
    header_ = "";
    transmissionDateTime_ = "";
    systemTraceAuditNumber_ = "";
    settlementDate_ = "";
    additionalId_ = "";
    networkManagementInfoCode_ = "";
    result_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Iso20022ControlResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            messageFunction_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            header_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            transmissionDateTime_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            systemTraceAuditNumber_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            settlementDate_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            additionalId_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            networkManagementInfoCode_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            result_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bbva.business.gateway.controldialogo.ControlDialogo.internal_static_b_gateway_v1_Iso20022ControlResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bbva.business.gateway.controldialogo.ControlDialogo.internal_static_b_gateway_v1_Iso20022ControlResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bbva.business.gateway.controldialogo.Iso20022ControlResponse.class, com.bbva.business.gateway.controldialogo.Iso20022ControlResponse.Builder.class);
  }

  public static final int MESSAGEFUNCTION_FIELD_NUMBER = 1;
  private volatile java.lang.Object messageFunction_;
  /**
   * <code>string messageFunction = 1;</code>
   */
  public java.lang.String getMessageFunction() {
    java.lang.Object ref = messageFunction_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageFunction_ = s;
      return s;
    }
  }
  /**
   * <code>string messageFunction = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMessageFunctionBytes() {
    java.lang.Object ref = messageFunction_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageFunction_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEADER_FIELD_NUMBER = 2;
  private volatile java.lang.Object header_;
  /**
   * <code>string header = 2;</code>
   */
  public java.lang.String getHeader() {
    java.lang.Object ref = header_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      header_ = s;
      return s;
    }
  }
  /**
   * <code>string header = 2;</code>
   */
  public com.google.protobuf.ByteString
      getHeaderBytes() {
    java.lang.Object ref = header_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      header_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSMISSIONDATETIME_FIELD_NUMBER = 3;
  private volatile java.lang.Object transmissionDateTime_;
  /**
   * <code>string transmissionDateTime = 3;</code>
   */
  public java.lang.String getTransmissionDateTime() {
    java.lang.Object ref = transmissionDateTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transmissionDateTime_ = s;
      return s;
    }
  }
  /**
   * <code>string transmissionDateTime = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTransmissionDateTimeBytes() {
    java.lang.Object ref = transmissionDateTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transmissionDateTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYSTEMTRACEAUDITNUMBER_FIELD_NUMBER = 4;
  private volatile java.lang.Object systemTraceAuditNumber_;
  /**
   * <code>string systemTraceAuditNumber = 4;</code>
   */
  public java.lang.String getSystemTraceAuditNumber() {
    java.lang.Object ref = systemTraceAuditNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      systemTraceAuditNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string systemTraceAuditNumber = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSystemTraceAuditNumberBytes() {
    java.lang.Object ref = systemTraceAuditNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      systemTraceAuditNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SETTLEMENTDATE_FIELD_NUMBER = 5;
  private volatile java.lang.Object settlementDate_;
  /**
   * <code>string settlementDate = 5;</code>
   */
  public java.lang.String getSettlementDate() {
    java.lang.Object ref = settlementDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      settlementDate_ = s;
      return s;
    }
  }
  /**
   * <code>string settlementDate = 5;</code>
   */
  public com.google.protobuf.ByteString
      getSettlementDateBytes() {
    java.lang.Object ref = settlementDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      settlementDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDITIONALID_FIELD_NUMBER = 6;
  private volatile java.lang.Object additionalId_;
  /**
   * <code>string additionalId = 6;</code>
   */
  public java.lang.String getAdditionalId() {
    java.lang.Object ref = additionalId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      additionalId_ = s;
      return s;
    }
  }
  /**
   * <code>string additionalId = 6;</code>
   */
  public com.google.protobuf.ByteString
      getAdditionalIdBytes() {
    java.lang.Object ref = additionalId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      additionalId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NETWORKMANAGEMENTINFOCODE_FIELD_NUMBER = 7;
  private volatile java.lang.Object networkManagementInfoCode_;
  /**
   * <code>string networkManagementInfoCode = 7;</code>
   */
  public java.lang.String getNetworkManagementInfoCode() {
    java.lang.Object ref = networkManagementInfoCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      networkManagementInfoCode_ = s;
      return s;
    }
  }
  /**
   * <code>string networkManagementInfoCode = 7;</code>
   */
  public com.google.protobuf.ByteString
      getNetworkManagementInfoCodeBytes() {
    java.lang.Object ref = networkManagementInfoCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      networkManagementInfoCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESULT_FIELD_NUMBER = 8;
  private volatile java.lang.Object result_;
  /**
   * <code>string result = 8;</code>
   */
  public java.lang.String getResult() {
    java.lang.Object ref = result_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      result_ = s;
      return s;
    }
  }
  /**
   * <code>string result = 8;</code>
   */
  public com.google.protobuf.ByteString
      getResultBytes() {
    java.lang.Object ref = result_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      result_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMessageFunctionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageFunction_);
    }
    if (!getHeaderBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, header_);
    }
    if (!getTransmissionDateTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, transmissionDateTime_);
    }
    if (!getSystemTraceAuditNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, systemTraceAuditNumber_);
    }
    if (!getSettlementDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, settlementDate_);
    }
    if (!getAdditionalIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, additionalId_);
    }
    if (!getNetworkManagementInfoCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, networkManagementInfoCode_);
    }
    if (!getResultBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, result_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMessageFunctionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageFunction_);
    }
    if (!getHeaderBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, header_);
    }
    if (!getTransmissionDateTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, transmissionDateTime_);
    }
    if (!getSystemTraceAuditNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, systemTraceAuditNumber_);
    }
    if (!getSettlementDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, settlementDate_);
    }
    if (!getAdditionalIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, additionalId_);
    }
    if (!getNetworkManagementInfoCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, networkManagementInfoCode_);
    }
    if (!getResultBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, result_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bbva.business.gateway.controldialogo.Iso20022ControlResponse)) {
      return super.equals(obj);
    }
    com.bbva.business.gateway.controldialogo.Iso20022ControlResponse other = (com.bbva.business.gateway.controldialogo.Iso20022ControlResponse) obj;

    boolean result = true;
    result = result && getMessageFunction()
        .equals(other.getMessageFunction());
    result = result && getHeader()
        .equals(other.getHeader());
    result = result && getTransmissionDateTime()
        .equals(other.getTransmissionDateTime());
    result = result && getSystemTraceAuditNumber()
        .equals(other.getSystemTraceAuditNumber());
    result = result && getSettlementDate()
        .equals(other.getSettlementDate());
    result = result && getAdditionalId()
        .equals(other.getAdditionalId());
    result = result && getNetworkManagementInfoCode()
        .equals(other.getNetworkManagementInfoCode());
    result = result && getResult()
        .equals(other.getResult());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGEFUNCTION_FIELD_NUMBER;
    hash = (53 * hash) + getMessageFunction().hashCode();
    hash = (37 * hash) + HEADER_FIELD_NUMBER;
    hash = (53 * hash) + getHeader().hashCode();
    hash = (37 * hash) + TRANSMISSIONDATETIME_FIELD_NUMBER;
    hash = (53 * hash) + getTransmissionDateTime().hashCode();
    hash = (37 * hash) + SYSTEMTRACEAUDITNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getSystemTraceAuditNumber().hashCode();
    hash = (37 * hash) + SETTLEMENTDATE_FIELD_NUMBER;
    hash = (53 * hash) + getSettlementDate().hashCode();
    hash = (37 * hash) + ADDITIONALID_FIELD_NUMBER;
    hash = (53 * hash) + getAdditionalId().hashCode();
    hash = (37 * hash) + NETWORKMANAGEMENTINFOCODE_FIELD_NUMBER;
    hash = (53 * hash) + getNetworkManagementInfoCode().hashCode();
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + getResult().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bbva.business.gateway.controldialogo.Iso20022ControlResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.controldialogo.Iso20022ControlResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.controldialogo.Iso20022ControlResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.controldialogo.Iso20022ControlResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.controldialogo.Iso20022ControlResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.controldialogo.Iso20022ControlResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.controldialogo.Iso20022ControlResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.controldialogo.Iso20022ControlResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.controldialogo.Iso20022ControlResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.controldialogo.Iso20022ControlResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.controldialogo.Iso20022ControlResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.controldialogo.Iso20022ControlResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bbva.business.gateway.controldialogo.Iso20022ControlResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code b.gateway.v1.Iso20022ControlResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:b.gateway.v1.Iso20022ControlResponse)
      com.bbva.business.gateway.controldialogo.Iso20022ControlResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbva.business.gateway.controldialogo.ControlDialogo.internal_static_b_gateway_v1_Iso20022ControlResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbva.business.gateway.controldialogo.ControlDialogo.internal_static_b_gateway_v1_Iso20022ControlResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbva.business.gateway.controldialogo.Iso20022ControlResponse.class, com.bbva.business.gateway.controldialogo.Iso20022ControlResponse.Builder.class);
    }

    // Construct using com.bbva.business.gateway.controldialogo.Iso20022ControlResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageFunction_ = "";

      header_ = "";

      transmissionDateTime_ = "";

      systemTraceAuditNumber_ = "";

      settlementDate_ = "";

      additionalId_ = "";

      networkManagementInfoCode_ = "";

      result_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bbva.business.gateway.controldialogo.ControlDialogo.internal_static_b_gateway_v1_Iso20022ControlResponse_descriptor;
    }

    @java.lang.Override
    public com.bbva.business.gateway.controldialogo.Iso20022ControlResponse getDefaultInstanceForType() {
      return com.bbva.business.gateway.controldialogo.Iso20022ControlResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.bbva.business.gateway.controldialogo.Iso20022ControlResponse build() {
      com.bbva.business.gateway.controldialogo.Iso20022ControlResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bbva.business.gateway.controldialogo.Iso20022ControlResponse buildPartial() {
      com.bbva.business.gateway.controldialogo.Iso20022ControlResponse result = new com.bbva.business.gateway.controldialogo.Iso20022ControlResponse(this);
      result.messageFunction_ = messageFunction_;
      result.header_ = header_;
      result.transmissionDateTime_ = transmissionDateTime_;
      result.systemTraceAuditNumber_ = systemTraceAuditNumber_;
      result.settlementDate_ = settlementDate_;
      result.additionalId_ = additionalId_;
      result.networkManagementInfoCode_ = networkManagementInfoCode_;
      result.result_ = result_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bbva.business.gateway.controldialogo.Iso20022ControlResponse) {
        return mergeFrom((com.bbva.business.gateway.controldialogo.Iso20022ControlResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bbva.business.gateway.controldialogo.Iso20022ControlResponse other) {
      if (other == com.bbva.business.gateway.controldialogo.Iso20022ControlResponse.getDefaultInstance()) return this;
      if (!other.getMessageFunction().isEmpty()) {
        messageFunction_ = other.messageFunction_;
        onChanged();
      }
      if (!other.getHeader().isEmpty()) {
        header_ = other.header_;
        onChanged();
      }
      if (!other.getTransmissionDateTime().isEmpty()) {
        transmissionDateTime_ = other.transmissionDateTime_;
        onChanged();
      }
      if (!other.getSystemTraceAuditNumber().isEmpty()) {
        systemTraceAuditNumber_ = other.systemTraceAuditNumber_;
        onChanged();
      }
      if (!other.getSettlementDate().isEmpty()) {
        settlementDate_ = other.settlementDate_;
        onChanged();
      }
      if (!other.getAdditionalId().isEmpty()) {
        additionalId_ = other.additionalId_;
        onChanged();
      }
      if (!other.getNetworkManagementInfoCode().isEmpty()) {
        networkManagementInfoCode_ = other.networkManagementInfoCode_;
        onChanged();
      }
      if (!other.getResult().isEmpty()) {
        result_ = other.result_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bbva.business.gateway.controldialogo.Iso20022ControlResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bbva.business.gateway.controldialogo.Iso20022ControlResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object messageFunction_ = "";
    /**
     * <code>string messageFunction = 1;</code>
     */
    public java.lang.String getMessageFunction() {
      java.lang.Object ref = messageFunction_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageFunction_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string messageFunction = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageFunctionBytes() {
      java.lang.Object ref = messageFunction_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageFunction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string messageFunction = 1;</code>
     */
    public Builder setMessageFunction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      messageFunction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string messageFunction = 1;</code>
     */
    public Builder clearMessageFunction() {
      
      messageFunction_ = getDefaultInstance().getMessageFunction();
      onChanged();
      return this;
    }
    /**
     * <code>string messageFunction = 1;</code>
     */
    public Builder setMessageFunctionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      messageFunction_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object header_ = "";
    /**
     * <code>string header = 2;</code>
     */
    public java.lang.String getHeader() {
      java.lang.Object ref = header_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        header_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string header = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHeaderBytes() {
      java.lang.Object ref = header_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        header_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string header = 2;</code>
     */
    public Builder setHeader(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      header_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string header = 2;</code>
     */
    public Builder clearHeader() {
      
      header_ = getDefaultInstance().getHeader();
      onChanged();
      return this;
    }
    /**
     * <code>string header = 2;</code>
     */
    public Builder setHeaderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      header_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object transmissionDateTime_ = "";
    /**
     * <code>string transmissionDateTime = 3;</code>
     */
    public java.lang.String getTransmissionDateTime() {
      java.lang.Object ref = transmissionDateTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transmissionDateTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transmissionDateTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTransmissionDateTimeBytes() {
      java.lang.Object ref = transmissionDateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transmissionDateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transmissionDateTime = 3;</code>
     */
    public Builder setTransmissionDateTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transmissionDateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transmissionDateTime = 3;</code>
     */
    public Builder clearTransmissionDateTime() {
      
      transmissionDateTime_ = getDefaultInstance().getTransmissionDateTime();
      onChanged();
      return this;
    }
    /**
     * <code>string transmissionDateTime = 3;</code>
     */
    public Builder setTransmissionDateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transmissionDateTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object systemTraceAuditNumber_ = "";
    /**
     * <code>string systemTraceAuditNumber = 4;</code>
     */
    public java.lang.String getSystemTraceAuditNumber() {
      java.lang.Object ref = systemTraceAuditNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        systemTraceAuditNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string systemTraceAuditNumber = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSystemTraceAuditNumberBytes() {
      java.lang.Object ref = systemTraceAuditNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        systemTraceAuditNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string systemTraceAuditNumber = 4;</code>
     */
    public Builder setSystemTraceAuditNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      systemTraceAuditNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string systemTraceAuditNumber = 4;</code>
     */
    public Builder clearSystemTraceAuditNumber() {
      
      systemTraceAuditNumber_ = getDefaultInstance().getSystemTraceAuditNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string systemTraceAuditNumber = 4;</code>
     */
    public Builder setSystemTraceAuditNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      systemTraceAuditNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object settlementDate_ = "";
    /**
     * <code>string settlementDate = 5;</code>
     */
    public java.lang.String getSettlementDate() {
      java.lang.Object ref = settlementDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        settlementDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string settlementDate = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSettlementDateBytes() {
      java.lang.Object ref = settlementDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        settlementDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string settlementDate = 5;</code>
     */
    public Builder setSettlementDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      settlementDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string settlementDate = 5;</code>
     */
    public Builder clearSettlementDate() {
      
      settlementDate_ = getDefaultInstance().getSettlementDate();
      onChanged();
      return this;
    }
    /**
     * <code>string settlementDate = 5;</code>
     */
    public Builder setSettlementDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      settlementDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object additionalId_ = "";
    /**
     * <code>string additionalId = 6;</code>
     */
    public java.lang.String getAdditionalId() {
      java.lang.Object ref = additionalId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        additionalId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string additionalId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAdditionalIdBytes() {
      java.lang.Object ref = additionalId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        additionalId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string additionalId = 6;</code>
     */
    public Builder setAdditionalId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      additionalId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string additionalId = 6;</code>
     */
    public Builder clearAdditionalId() {
      
      additionalId_ = getDefaultInstance().getAdditionalId();
      onChanged();
      return this;
    }
    /**
     * <code>string additionalId = 6;</code>
     */
    public Builder setAdditionalIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      additionalId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object networkManagementInfoCode_ = "";
    /**
     * <code>string networkManagementInfoCode = 7;</code>
     */
    public java.lang.String getNetworkManagementInfoCode() {
      java.lang.Object ref = networkManagementInfoCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        networkManagementInfoCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string networkManagementInfoCode = 7;</code>
     */
    public com.google.protobuf.ByteString
        getNetworkManagementInfoCodeBytes() {
      java.lang.Object ref = networkManagementInfoCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        networkManagementInfoCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string networkManagementInfoCode = 7;</code>
     */
    public Builder setNetworkManagementInfoCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      networkManagementInfoCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string networkManagementInfoCode = 7;</code>
     */
    public Builder clearNetworkManagementInfoCode() {
      
      networkManagementInfoCode_ = getDefaultInstance().getNetworkManagementInfoCode();
      onChanged();
      return this;
    }
    /**
     * <code>string networkManagementInfoCode = 7;</code>
     */
    public Builder setNetworkManagementInfoCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      networkManagementInfoCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object result_ = "";
    /**
     * <code>string result = 8;</code>
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        result_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string result = 8;</code>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string result = 8;</code>
     */
    public Builder setResult(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      result_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string result = 8;</code>
     */
    public Builder clearResult() {
      
      result_ = getDefaultInstance().getResult();
      onChanged();
      return this;
    }
    /**
     * <code>string result = 8;</code>
     */
    public Builder setResultBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      result_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:b.gateway.v1.Iso20022ControlResponse)
  }

  // @@protoc_insertion_point(class_scope:b.gateway.v1.Iso20022ControlResponse)
  private static final com.bbva.business.gateway.controldialogo.Iso20022ControlResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bbva.business.gateway.controldialogo.Iso20022ControlResponse();
  }

  public static com.bbva.business.gateway.controldialogo.Iso20022ControlResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Iso20022ControlResponse>
      PARSER = new com.google.protobuf.AbstractParser<Iso20022ControlResponse>() {
    @java.lang.Override
    public Iso20022ControlResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Iso20022ControlResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Iso20022ControlResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Iso20022ControlResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bbva.business.gateway.controldialogo.Iso20022ControlResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

