// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controlDialogo.proto

package com.bbva.business.gateway.controldialogo;

public interface Iso20022ControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.Iso20022ControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageFunction = 1;</code>
   */
  java.lang.String getMessageFunction();
  /**
   * <code>string messageFunction = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageFunctionBytes();

  /**
   * <code>string header = 2;</code>
   */
  java.lang.String getHeader();
  /**
   * <code>string header = 2;</code>
   */
  com.google.protobuf.ByteString
      getHeaderBytes();

  /**
   * <code>string transmissionDateTime = 3;</code>
   */
  java.lang.String getTransmissionDateTime();
  /**
   * <code>string transmissionDateTime = 3;</code>
   */
  com.google.protobuf.ByteString
      getTransmissionDateTimeBytes();

  /**
   * <code>string systemTraceAuditNumber = 4;</code>
   */
  java.lang.String getSystemTraceAuditNumber();
  /**
   * <code>string systemTraceAuditNumber = 4;</code>
   */
  com.google.protobuf.ByteString
      getSystemTraceAuditNumberBytes();

  /**
   * <code>string settlementDate = 5;</code>
   */
  java.lang.String getSettlementDate();
  /**
   * <code>string settlementDate = 5;</code>
   */
  com.google.protobuf.ByteString
      getSettlementDateBytes();

  /**
   * <code>string additionalId = 6;</code>
   */
  java.lang.String getAdditionalId();
  /**
   * <code>string additionalId = 6;</code>
   */
  com.google.protobuf.ByteString
      getAdditionalIdBytes();

  /**
   * <code>string networkManagementInfoCode = 7;</code>
   */
  java.lang.String getNetworkManagementInfoCode();
  /**
   * <code>string networkManagementInfoCode = 7;</code>
   */
  com.google.protobuf.ByteString
      getNetworkManagementInfoCodeBytes();
}
