// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

public interface AccountFromOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.AccountFrom)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue accountId = 1;</code>
   */
  boolean hasAccountId();
  /**
   * <code>.google.protobuf.StringValue accountId = 1;</code>
   */
  com.google.protobuf.StringValue getAccountId();
  /**
   * <code>.google.protobuf.StringValue accountId = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getAccountIdOrBuilder();

  /**
   * <code>.google.protobuf.StringValue accountType = 2;</code>
   */
  boolean hasAccountType();
  /**
   * <code>.google.protobuf.StringValue accountType = 2;</code>
   */
  com.google.protobuf.StringValue getAccountType();
  /**
   * <code>.google.protobuf.StringValue accountType = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getAccountTypeOrBuilder();
}
