// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

public interface AdjustmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.Adjustment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue key = 1;</code>
   */
  boolean hasKey();
  /**
   * <code>.google.protobuf.StringValue key = 1;</code>
   */
  com.google.protobuf.StringValue getKey();
  /**
   * <code>.google.protobuf.StringValue key = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getKeyOrBuilder();

  /**
   * <code>.google.protobuf.StringValue additionalType = 2;</code>
   */
  boolean hasAdditionalType();
  /**
   * <code>.google.protobuf.StringValue additionalType = 2;</code>
   */
  com.google.protobuf.StringValue getAdditionalType();
  /**
   * <code>.google.protobuf.StringValue additionalType = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getAdditionalTypeOrBuilder();

  /**
   * <code>.google.protobuf.DoubleValue adjustmentAmount = 3;</code>
   */
  boolean hasAdjustmentAmount();
  /**
   * <code>.google.protobuf.DoubleValue adjustmentAmount = 3;</code>
   */
  com.google.protobuf.DoubleValue getAdjustmentAmount();
  /**
   * <code>.google.protobuf.DoubleValue adjustmentAmount = 3;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getAdjustmentAmountOrBuilder();
}
