// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

/**
 * Protobuf type {@code b.gateway.v1.CardholderVerificationCapability}
 */
public  final class CardholderVerificationCapability extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:b.gateway.v1.CardholderVerificationCapability)
    CardholderVerificationCapabilityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CardholderVerificationCapability.newBuilder() to construct.
  private CardholderVerificationCapability(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CardholderVerificationCapability() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CardholderVerificationCapability(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (capability_ != null) {
              subBuilder = capability_.toBuilder();
            }
            capability_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(capability_);
              capability_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_CardholderVerificationCapability_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_CardholderVerificationCapability_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bbva.business.gateway.iso20022.CardholderVerificationCapability.class, com.bbva.business.gateway.iso20022.CardholderVerificationCapability.Builder.class);
  }

  public static final int CAPABILITY_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue capability_;
  /**
   * <code>.google.protobuf.StringValue capability = 1;</code>
   */
  public boolean hasCapability() {
    return capability_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue capability = 1;</code>
   */
  public com.google.protobuf.StringValue getCapability() {
    return capability_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : capability_;
  }
  /**
   * <code>.google.protobuf.StringValue capability = 1;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getCapabilityOrBuilder() {
    return getCapability();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (capability_ != null) {
      output.writeMessage(1, getCapability());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (capability_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCapability());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bbva.business.gateway.iso20022.CardholderVerificationCapability)) {
      return super.equals(obj);
    }
    com.bbva.business.gateway.iso20022.CardholderVerificationCapability other = (com.bbva.business.gateway.iso20022.CardholderVerificationCapability) obj;

    boolean result = true;
    result = result && (hasCapability() == other.hasCapability());
    if (hasCapability()) {
      result = result && getCapability()
          .equals(other.getCapability());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCapability()) {
      hash = (37 * hash) + CAPABILITY_FIELD_NUMBER;
      hash = (53 * hash) + getCapability().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bbva.business.gateway.iso20022.CardholderVerificationCapability parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.CardholderVerificationCapability parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.CardholderVerificationCapability parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.CardholderVerificationCapability parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.CardholderVerificationCapability parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.CardholderVerificationCapability parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.CardholderVerificationCapability parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.CardholderVerificationCapability parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.CardholderVerificationCapability parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.CardholderVerificationCapability parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.CardholderVerificationCapability parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.CardholderVerificationCapability parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bbva.business.gateway.iso20022.CardholderVerificationCapability prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code b.gateway.v1.CardholderVerificationCapability}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:b.gateway.v1.CardholderVerificationCapability)
      com.bbva.business.gateway.iso20022.CardholderVerificationCapabilityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_CardholderVerificationCapability_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_CardholderVerificationCapability_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbva.business.gateway.iso20022.CardholderVerificationCapability.class, com.bbva.business.gateway.iso20022.CardholderVerificationCapability.Builder.class);
    }

    // Construct using com.bbva.business.gateway.iso20022.CardholderVerificationCapability.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (capabilityBuilder_ == null) {
        capability_ = null;
      } else {
        capability_ = null;
        capabilityBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_CardholderVerificationCapability_descriptor;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.CardholderVerificationCapability getDefaultInstanceForType() {
      return com.bbva.business.gateway.iso20022.CardholderVerificationCapability.getDefaultInstance();
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.CardholderVerificationCapability build() {
      com.bbva.business.gateway.iso20022.CardholderVerificationCapability result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.CardholderVerificationCapability buildPartial() {
      com.bbva.business.gateway.iso20022.CardholderVerificationCapability result = new com.bbva.business.gateway.iso20022.CardholderVerificationCapability(this);
      if (capabilityBuilder_ == null) {
        result.capability_ = capability_;
      } else {
        result.capability_ = capabilityBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bbva.business.gateway.iso20022.CardholderVerificationCapability) {
        return mergeFrom((com.bbva.business.gateway.iso20022.CardholderVerificationCapability)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bbva.business.gateway.iso20022.CardholderVerificationCapability other) {
      if (other == com.bbva.business.gateway.iso20022.CardholderVerificationCapability.getDefaultInstance()) return this;
      if (other.hasCapability()) {
        mergeCapability(other.getCapability());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bbva.business.gateway.iso20022.CardholderVerificationCapability parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bbva.business.gateway.iso20022.CardholderVerificationCapability) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.StringValue capability_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> capabilityBuilder_;
    /**
     * <code>.google.protobuf.StringValue capability = 1;</code>
     */
    public boolean hasCapability() {
      return capabilityBuilder_ != null || capability_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue capability = 1;</code>
     */
    public com.google.protobuf.StringValue getCapability() {
      if (capabilityBuilder_ == null) {
        return capability_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : capability_;
      } else {
        return capabilityBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue capability = 1;</code>
     */
    public Builder setCapability(com.google.protobuf.StringValue value) {
      if (capabilityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        capability_ = value;
        onChanged();
      } else {
        capabilityBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue capability = 1;</code>
     */
    public Builder setCapability(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (capabilityBuilder_ == null) {
        capability_ = builderForValue.build();
        onChanged();
      } else {
        capabilityBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue capability = 1;</code>
     */
    public Builder mergeCapability(com.google.protobuf.StringValue value) {
      if (capabilityBuilder_ == null) {
        if (capability_ != null) {
          capability_ =
            com.google.protobuf.StringValue.newBuilder(capability_).mergeFrom(value).buildPartial();
        } else {
          capability_ = value;
        }
        onChanged();
      } else {
        capabilityBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue capability = 1;</code>
     */
    public Builder clearCapability() {
      if (capabilityBuilder_ == null) {
        capability_ = null;
        onChanged();
      } else {
        capability_ = null;
        capabilityBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue capability = 1;</code>
     */
    public com.google.protobuf.StringValue.Builder getCapabilityBuilder() {
      
      onChanged();
      return getCapabilityFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue capability = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getCapabilityOrBuilder() {
      if (capabilityBuilder_ != null) {
        return capabilityBuilder_.getMessageOrBuilder();
      } else {
        return capability_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : capability_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue capability = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getCapabilityFieldBuilder() {
      if (capabilityBuilder_ == null) {
        capabilityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getCapability(),
                getParentForChildren(),
                isClean());
        capability_ = null;
      }
      return capabilityBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:b.gateway.v1.CardholderVerificationCapability)
  }

  // @@protoc_insertion_point(class_scope:b.gateway.v1.CardholderVerificationCapability)
  private static final com.bbva.business.gateway.iso20022.CardholderVerificationCapability DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bbva.business.gateway.iso20022.CardholderVerificationCapability();
  }

  public static com.bbva.business.gateway.iso20022.CardholderVerificationCapability getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CardholderVerificationCapability>
      PARSER = new com.google.protobuf.AbstractParser<CardholderVerificationCapability>() {
    @java.lang.Override
    public CardholderVerificationCapability parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CardholderVerificationCapability(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CardholderVerificationCapability> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CardholderVerificationCapability> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bbva.business.gateway.iso20022.CardholderVerificationCapability getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

