// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

public interface CardholderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.Cardholder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.b.gateway.v1.CardholderName cardholderName = 1;</code>
   */
  boolean hasCardholderName();
  /**
   * <code>.b.gateway.v1.CardholderName cardholderName = 1;</code>
   */
  com.bbva.business.gateway.iso20022.CardholderName getCardholderName();
  /**
   * <code>.b.gateway.v1.CardholderName cardholderName = 1;</code>
   */
  com.bbva.business.gateway.iso20022.CardholderNameOrBuilder getCardholderNameOrBuilder();

  /**
   * <code>repeated .b.gateway.v1.IdentificationCardholder identification = 2;</code>
   */
  java.util.List<com.bbva.business.gateway.iso20022.IdentificationCardholder> 
      getIdentificationList();
  /**
   * <code>repeated .b.gateway.v1.IdentificationCardholder identification = 2;</code>
   */
  com.bbva.business.gateway.iso20022.IdentificationCardholder getIdentification(int index);
  /**
   * <code>repeated .b.gateway.v1.IdentificationCardholder identification = 2;</code>
   */
  int getIdentificationCount();
  /**
   * <code>repeated .b.gateway.v1.IdentificationCardholder identification = 2;</code>
   */
  java.util.List<? extends com.bbva.business.gateway.iso20022.IdentificationCardholderOrBuilder> 
      getIdentificationOrBuilderList();
  /**
   * <code>repeated .b.gateway.v1.IdentificationCardholder identification = 2;</code>
   */
  com.bbva.business.gateway.iso20022.IdentificationCardholderOrBuilder getIdentificationOrBuilder(
      int index);

  /**
   * <code>.b.gateway.v1.ContactInformation contactInformation = 3;</code>
   */
  boolean hasContactInformation();
  /**
   * <code>.b.gateway.v1.ContactInformation contactInformation = 3;</code>
   */
  com.bbva.business.gateway.iso20022.ContactInformation getContactInformation();
  /**
   * <code>.b.gateway.v1.ContactInformation contactInformation = 3;</code>
   */
  com.bbva.business.gateway.iso20022.ContactInformationOrBuilder getContactInformationOrBuilder();
}
