// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

/**
 * Protobuf type {@code b.gateway.v1.CustomDataLocal}
 */
public  final class CustomDataLocal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:b.gateway.v1.CustomDataLocal)
    CustomDataLocalOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CustomDataLocal.newBuilder() to construct.
  private CustomDataLocal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CustomDataLocal() {
    additionalData_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CustomDataLocal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              additionalData_ = new java.util.ArrayList<com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal>();
              mutable_bitField0_ |= 0x00000001;
            }
            additionalData_.add(
                input.readMessage(com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        additionalData_ = java.util.Collections.unmodifiableList(additionalData_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_CustomDataLocal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_CustomDataLocal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bbva.business.gateway.iso20022.CustomDataLocal.class, com.bbva.business.gateway.iso20022.CustomDataLocal.Builder.class);
  }

  public static final int ADDITIONALDATA_FIELD_NUMBER = 1;
  private java.util.List<com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal> additionalData_;
  /**
   * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
   */
  public java.util.List<com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal> getAdditionalDataList() {
    return additionalData_;
  }
  /**
   * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
   */
  public java.util.List<? extends com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocalOrBuilder> 
      getAdditionalDataOrBuilderList() {
    return additionalData_;
  }
  /**
   * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
   */
  public int getAdditionalDataCount() {
    return additionalData_.size();
  }
  /**
   * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
   */
  public com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal getAdditionalData(int index) {
    return additionalData_.get(index);
  }
  /**
   * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
   */
  public com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocalOrBuilder getAdditionalDataOrBuilder(
      int index) {
    return additionalData_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < additionalData_.size(); i++) {
      output.writeMessage(1, additionalData_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < additionalData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, additionalData_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bbva.business.gateway.iso20022.CustomDataLocal)) {
      return super.equals(obj);
    }
    com.bbva.business.gateway.iso20022.CustomDataLocal other = (com.bbva.business.gateway.iso20022.CustomDataLocal) obj;

    boolean result = true;
    result = result && getAdditionalDataList()
        .equals(other.getAdditionalDataList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAdditionalDataCount() > 0) {
      hash = (37 * hash) + ADDITIONALDATA_FIELD_NUMBER;
      hash = (53 * hash) + getAdditionalDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bbva.business.gateway.iso20022.CustomDataLocal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.CustomDataLocal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.CustomDataLocal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.CustomDataLocal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.CustomDataLocal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.CustomDataLocal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.CustomDataLocal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.CustomDataLocal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.CustomDataLocal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.CustomDataLocal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.CustomDataLocal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.CustomDataLocal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bbva.business.gateway.iso20022.CustomDataLocal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code b.gateway.v1.CustomDataLocal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:b.gateway.v1.CustomDataLocal)
      com.bbva.business.gateway.iso20022.CustomDataLocalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_CustomDataLocal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_CustomDataLocal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbva.business.gateway.iso20022.CustomDataLocal.class, com.bbva.business.gateway.iso20022.CustomDataLocal.Builder.class);
    }

    // Construct using com.bbva.business.gateway.iso20022.CustomDataLocal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAdditionalDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (additionalDataBuilder_ == null) {
        additionalData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        additionalDataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_CustomDataLocal_descriptor;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.CustomDataLocal getDefaultInstanceForType() {
      return com.bbva.business.gateway.iso20022.CustomDataLocal.getDefaultInstance();
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.CustomDataLocal build() {
      com.bbva.business.gateway.iso20022.CustomDataLocal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.CustomDataLocal buildPartial() {
      com.bbva.business.gateway.iso20022.CustomDataLocal result = new com.bbva.business.gateway.iso20022.CustomDataLocal(this);
      int from_bitField0_ = bitField0_;
      if (additionalDataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          additionalData_ = java.util.Collections.unmodifiableList(additionalData_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.additionalData_ = additionalData_;
      } else {
        result.additionalData_ = additionalDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bbva.business.gateway.iso20022.CustomDataLocal) {
        return mergeFrom((com.bbva.business.gateway.iso20022.CustomDataLocal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bbva.business.gateway.iso20022.CustomDataLocal other) {
      if (other == com.bbva.business.gateway.iso20022.CustomDataLocal.getDefaultInstance()) return this;
      if (additionalDataBuilder_ == null) {
        if (!other.additionalData_.isEmpty()) {
          if (additionalData_.isEmpty()) {
            additionalData_ = other.additionalData_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAdditionalDataIsMutable();
            additionalData_.addAll(other.additionalData_);
          }
          onChanged();
        }
      } else {
        if (!other.additionalData_.isEmpty()) {
          if (additionalDataBuilder_.isEmpty()) {
            additionalDataBuilder_.dispose();
            additionalDataBuilder_ = null;
            additionalData_ = other.additionalData_;
            bitField0_ = (bitField0_ & ~0x00000001);
            additionalDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAdditionalDataFieldBuilder() : null;
          } else {
            additionalDataBuilder_.addAllMessages(other.additionalData_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bbva.business.gateway.iso20022.CustomDataLocal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bbva.business.gateway.iso20022.CustomDataLocal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal> additionalData_ =
      java.util.Collections.emptyList();
    private void ensureAdditionalDataIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        additionalData_ = new java.util.ArrayList<com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal>(additionalData_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal, com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal.Builder, com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocalOrBuilder> additionalDataBuilder_;

    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public java.util.List<com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal> getAdditionalDataList() {
      if (additionalDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(additionalData_);
      } else {
        return additionalDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public int getAdditionalDataCount() {
      if (additionalDataBuilder_ == null) {
        return additionalData_.size();
      } else {
        return additionalDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal getAdditionalData(int index) {
      if (additionalDataBuilder_ == null) {
        return additionalData_.get(index);
      } else {
        return additionalDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public Builder setAdditionalData(
        int index, com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal value) {
      if (additionalDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdditionalDataIsMutable();
        additionalData_.set(index, value);
        onChanged();
      } else {
        additionalDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public Builder setAdditionalData(
        int index, com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal.Builder builderForValue) {
      if (additionalDataBuilder_ == null) {
        ensureAdditionalDataIsMutable();
        additionalData_.set(index, builderForValue.build());
        onChanged();
      } else {
        additionalDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public Builder addAdditionalData(com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal value) {
      if (additionalDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdditionalDataIsMutable();
        additionalData_.add(value);
        onChanged();
      } else {
        additionalDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public Builder addAdditionalData(
        int index, com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal value) {
      if (additionalDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdditionalDataIsMutable();
        additionalData_.add(index, value);
        onChanged();
      } else {
        additionalDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public Builder addAdditionalData(
        com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal.Builder builderForValue) {
      if (additionalDataBuilder_ == null) {
        ensureAdditionalDataIsMutable();
        additionalData_.add(builderForValue.build());
        onChanged();
      } else {
        additionalDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public Builder addAdditionalData(
        int index, com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal.Builder builderForValue) {
      if (additionalDataBuilder_ == null) {
        ensureAdditionalDataIsMutable();
        additionalData_.add(index, builderForValue.build());
        onChanged();
      } else {
        additionalDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public Builder addAllAdditionalData(
        java.lang.Iterable<? extends com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal> values) {
      if (additionalDataBuilder_ == null) {
        ensureAdditionalDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, additionalData_);
        onChanged();
      } else {
        additionalDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public Builder clearAdditionalData() {
      if (additionalDataBuilder_ == null) {
        additionalData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        additionalDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public Builder removeAdditionalData(int index) {
      if (additionalDataBuilder_ == null) {
        ensureAdditionalDataIsMutable();
        additionalData_.remove(index);
        onChanged();
      } else {
        additionalDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal.Builder getAdditionalDataBuilder(
        int index) {
      return getAdditionalDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocalOrBuilder getAdditionalDataOrBuilder(
        int index) {
      if (additionalDataBuilder_ == null) {
        return additionalData_.get(index);  } else {
        return additionalDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public java.util.List<? extends com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocalOrBuilder> 
         getAdditionalDataOrBuilderList() {
      if (additionalDataBuilder_ != null) {
        return additionalDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(additionalData_);
      }
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal.Builder addAdditionalDataBuilder() {
      return getAdditionalDataFieldBuilder().addBuilder(
          com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal.getDefaultInstance());
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal.Builder addAdditionalDataBuilder(
        int index) {
      return getAdditionalDataFieldBuilder().addBuilder(
          index, com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal.getDefaultInstance());
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalDataCustomDataLocal additionalData = 1;</code>
     */
    public java.util.List<com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal.Builder> 
         getAdditionalDataBuilderList() {
      return getAdditionalDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal, com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal.Builder, com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocalOrBuilder> 
        getAdditionalDataFieldBuilder() {
      if (additionalDataBuilder_ == null) {
        additionalDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal, com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocal.Builder, com.bbva.business.gateway.iso20022.AdditionalDataCustomDataLocalOrBuilder>(
                additionalData_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        additionalData_ = null;
      }
      return additionalDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:b.gateway.v1.CustomDataLocal)
  }

  // @@protoc_insertion_point(class_scope:b.gateway.v1.CustomDataLocal)
  private static final com.bbva.business.gateway.iso20022.CustomDataLocal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bbva.business.gateway.iso20022.CustomDataLocal();
  }

  public static com.bbva.business.gateway.iso20022.CustomDataLocal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CustomDataLocal>
      PARSER = new com.google.protobuf.AbstractParser<CustomDataLocal>() {
    @java.lang.Override
    public CustomDataLocal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CustomDataLocal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CustomDataLocal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CustomDataLocal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bbva.business.gateway.iso20022.CustomDataLocal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

