// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

/**
 * Protobuf type {@code b.gateway.v1.IdentificationCardholder}
 */
public  final class IdentificationCardholder extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:b.gateway.v1.IdentificationCardholder)
    IdentificationCardholderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IdentificationCardholder.newBuilder() to construct.
  private IdentificationCardholder(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IdentificationCardholder() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private IdentificationCardholder(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (identificationValue_ != null) {
              subBuilder = identificationValue_.toBuilder();
            }
            identificationValue_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(identificationValue_);
              identificationValue_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_IdentificationCardholder_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_IdentificationCardholder_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bbva.business.gateway.iso20022.IdentificationCardholder.class, com.bbva.business.gateway.iso20022.IdentificationCardholder.Builder.class);
  }

  public static final int IDENTIFICATIONVALUE_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue identificationValue_;
  /**
   * <code>.google.protobuf.StringValue identificationValue = 1;</code>
   */
  public boolean hasIdentificationValue() {
    return identificationValue_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue identificationValue = 1;</code>
   */
  public com.google.protobuf.StringValue getIdentificationValue() {
    return identificationValue_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : identificationValue_;
  }
  /**
   * <code>.google.protobuf.StringValue identificationValue = 1;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getIdentificationValueOrBuilder() {
    return getIdentificationValue();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (identificationValue_ != null) {
      output.writeMessage(1, getIdentificationValue());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (identificationValue_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getIdentificationValue());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bbva.business.gateway.iso20022.IdentificationCardholder)) {
      return super.equals(obj);
    }
    com.bbva.business.gateway.iso20022.IdentificationCardholder other = (com.bbva.business.gateway.iso20022.IdentificationCardholder) obj;

    boolean result = true;
    result = result && (hasIdentificationValue() == other.hasIdentificationValue());
    if (hasIdentificationValue()) {
      result = result && getIdentificationValue()
          .equals(other.getIdentificationValue());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIdentificationValue()) {
      hash = (37 * hash) + IDENTIFICATIONVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getIdentificationValue().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bbva.business.gateway.iso20022.IdentificationCardholder parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.IdentificationCardholder parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.IdentificationCardholder parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.IdentificationCardholder parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.IdentificationCardholder parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.IdentificationCardholder parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.IdentificationCardholder parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.IdentificationCardholder parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.IdentificationCardholder parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.IdentificationCardholder parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.IdentificationCardholder parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.IdentificationCardholder parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bbva.business.gateway.iso20022.IdentificationCardholder prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code b.gateway.v1.IdentificationCardholder}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:b.gateway.v1.IdentificationCardholder)
      com.bbva.business.gateway.iso20022.IdentificationCardholderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_IdentificationCardholder_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_IdentificationCardholder_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbva.business.gateway.iso20022.IdentificationCardholder.class, com.bbva.business.gateway.iso20022.IdentificationCardholder.Builder.class);
    }

    // Construct using com.bbva.business.gateway.iso20022.IdentificationCardholder.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (identificationValueBuilder_ == null) {
        identificationValue_ = null;
      } else {
        identificationValue_ = null;
        identificationValueBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_IdentificationCardholder_descriptor;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.IdentificationCardholder getDefaultInstanceForType() {
      return com.bbva.business.gateway.iso20022.IdentificationCardholder.getDefaultInstance();
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.IdentificationCardholder build() {
      com.bbva.business.gateway.iso20022.IdentificationCardholder result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.IdentificationCardholder buildPartial() {
      com.bbva.business.gateway.iso20022.IdentificationCardholder result = new com.bbva.business.gateway.iso20022.IdentificationCardholder(this);
      if (identificationValueBuilder_ == null) {
        result.identificationValue_ = identificationValue_;
      } else {
        result.identificationValue_ = identificationValueBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bbva.business.gateway.iso20022.IdentificationCardholder) {
        return mergeFrom((com.bbva.business.gateway.iso20022.IdentificationCardholder)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bbva.business.gateway.iso20022.IdentificationCardholder other) {
      if (other == com.bbva.business.gateway.iso20022.IdentificationCardholder.getDefaultInstance()) return this;
      if (other.hasIdentificationValue()) {
        mergeIdentificationValue(other.getIdentificationValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bbva.business.gateway.iso20022.IdentificationCardholder parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bbva.business.gateway.iso20022.IdentificationCardholder) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.StringValue identificationValue_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> identificationValueBuilder_;
    /**
     * <code>.google.protobuf.StringValue identificationValue = 1;</code>
     */
    public boolean hasIdentificationValue() {
      return identificationValueBuilder_ != null || identificationValue_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue identificationValue = 1;</code>
     */
    public com.google.protobuf.StringValue getIdentificationValue() {
      if (identificationValueBuilder_ == null) {
        return identificationValue_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : identificationValue_;
      } else {
        return identificationValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue identificationValue = 1;</code>
     */
    public Builder setIdentificationValue(com.google.protobuf.StringValue value) {
      if (identificationValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        identificationValue_ = value;
        onChanged();
      } else {
        identificationValueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue identificationValue = 1;</code>
     */
    public Builder setIdentificationValue(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (identificationValueBuilder_ == null) {
        identificationValue_ = builderForValue.build();
        onChanged();
      } else {
        identificationValueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue identificationValue = 1;</code>
     */
    public Builder mergeIdentificationValue(com.google.protobuf.StringValue value) {
      if (identificationValueBuilder_ == null) {
        if (identificationValue_ != null) {
          identificationValue_ =
            com.google.protobuf.StringValue.newBuilder(identificationValue_).mergeFrom(value).buildPartial();
        } else {
          identificationValue_ = value;
        }
        onChanged();
      } else {
        identificationValueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue identificationValue = 1;</code>
     */
    public Builder clearIdentificationValue() {
      if (identificationValueBuilder_ == null) {
        identificationValue_ = null;
        onChanged();
      } else {
        identificationValue_ = null;
        identificationValueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue identificationValue = 1;</code>
     */
    public com.google.protobuf.StringValue.Builder getIdentificationValueBuilder() {
      
      onChanged();
      return getIdentificationValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue identificationValue = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getIdentificationValueOrBuilder() {
      if (identificationValueBuilder_ != null) {
        return identificationValueBuilder_.getMessageOrBuilder();
      } else {
        return identificationValue_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : identificationValue_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue identificationValue = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getIdentificationValueFieldBuilder() {
      if (identificationValueBuilder_ == null) {
        identificationValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getIdentificationValue(),
                getParentForChildren(),
                isClean());
        identificationValue_ = null;
      }
      return identificationValueBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:b.gateway.v1.IdentificationCardholder)
  }

  // @@protoc_insertion_point(class_scope:b.gateway.v1.IdentificationCardholder)
  private static final com.bbva.business.gateway.iso20022.IdentificationCardholder DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bbva.business.gateway.iso20022.IdentificationCardholder();
  }

  public static com.bbva.business.gateway.iso20022.IdentificationCardholder getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IdentificationCardholder>
      PARSER = new com.google.protobuf.AbstractParser<IdentificationCardholder>() {
    @java.lang.Override
    public IdentificationCardholder parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IdentificationCardholder(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<IdentificationCardholder> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IdentificationCardholder> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bbva.business.gateway.iso20022.IdentificationCardholder getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

