// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

/**
 * Protobuf type {@code b.gateway.v1.KEKId}
 */
public  final class KEKId extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:b.gateway.v1.KEKId)
    KEKIdOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KEKId.newBuilder() to construct.
  private KEKId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KEKId() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KEKId(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (keyId_ != null) {
              subBuilder = keyId_.toBuilder();
            }
            keyId_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(keyId_);
              keyId_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_KEKId_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_KEKId_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bbva.business.gateway.iso20022.KEKId.class, com.bbva.business.gateway.iso20022.KEKId.Builder.class);
  }

  public static final int KEYID_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue keyId_;
  /**
   * <code>.google.protobuf.StringValue keyId = 1;</code>
   */
  public boolean hasKeyId() {
    return keyId_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue keyId = 1;</code>
   */
  public com.google.protobuf.StringValue getKeyId() {
    return keyId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : keyId_;
  }
  /**
   * <code>.google.protobuf.StringValue keyId = 1;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getKeyIdOrBuilder() {
    return getKeyId();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (keyId_ != null) {
      output.writeMessage(1, getKeyId());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (keyId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getKeyId());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bbva.business.gateway.iso20022.KEKId)) {
      return super.equals(obj);
    }
    com.bbva.business.gateway.iso20022.KEKId other = (com.bbva.business.gateway.iso20022.KEKId) obj;

    boolean result = true;
    result = result && (hasKeyId() == other.hasKeyId());
    if (hasKeyId()) {
      result = result && getKeyId()
          .equals(other.getKeyId());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasKeyId()) {
      hash = (37 * hash) + KEYID_FIELD_NUMBER;
      hash = (53 * hash) + getKeyId().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bbva.business.gateway.iso20022.KEKId parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.KEKId parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.KEKId parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.KEKId parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.KEKId parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.KEKId parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.KEKId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.KEKId parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.KEKId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.KEKId parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.KEKId parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.KEKId parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bbva.business.gateway.iso20022.KEKId prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code b.gateway.v1.KEKId}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:b.gateway.v1.KEKId)
      com.bbva.business.gateway.iso20022.KEKIdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_KEKId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_KEKId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbva.business.gateway.iso20022.KEKId.class, com.bbva.business.gateway.iso20022.KEKId.Builder.class);
    }

    // Construct using com.bbva.business.gateway.iso20022.KEKId.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (keyIdBuilder_ == null) {
        keyId_ = null;
      } else {
        keyId_ = null;
        keyIdBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_KEKId_descriptor;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.KEKId getDefaultInstanceForType() {
      return com.bbva.business.gateway.iso20022.KEKId.getDefaultInstance();
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.KEKId build() {
      com.bbva.business.gateway.iso20022.KEKId result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.KEKId buildPartial() {
      com.bbva.business.gateway.iso20022.KEKId result = new com.bbva.business.gateway.iso20022.KEKId(this);
      if (keyIdBuilder_ == null) {
        result.keyId_ = keyId_;
      } else {
        result.keyId_ = keyIdBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bbva.business.gateway.iso20022.KEKId) {
        return mergeFrom((com.bbva.business.gateway.iso20022.KEKId)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bbva.business.gateway.iso20022.KEKId other) {
      if (other == com.bbva.business.gateway.iso20022.KEKId.getDefaultInstance()) return this;
      if (other.hasKeyId()) {
        mergeKeyId(other.getKeyId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bbva.business.gateway.iso20022.KEKId parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bbva.business.gateway.iso20022.KEKId) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.StringValue keyId_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> keyIdBuilder_;
    /**
     * <code>.google.protobuf.StringValue keyId = 1;</code>
     */
    public boolean hasKeyId() {
      return keyIdBuilder_ != null || keyId_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue keyId = 1;</code>
     */
    public com.google.protobuf.StringValue getKeyId() {
      if (keyIdBuilder_ == null) {
        return keyId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : keyId_;
      } else {
        return keyIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue keyId = 1;</code>
     */
    public Builder setKeyId(com.google.protobuf.StringValue value) {
      if (keyIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        keyId_ = value;
        onChanged();
      } else {
        keyIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue keyId = 1;</code>
     */
    public Builder setKeyId(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (keyIdBuilder_ == null) {
        keyId_ = builderForValue.build();
        onChanged();
      } else {
        keyIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue keyId = 1;</code>
     */
    public Builder mergeKeyId(com.google.protobuf.StringValue value) {
      if (keyIdBuilder_ == null) {
        if (keyId_ != null) {
          keyId_ =
            com.google.protobuf.StringValue.newBuilder(keyId_).mergeFrom(value).buildPartial();
        } else {
          keyId_ = value;
        }
        onChanged();
      } else {
        keyIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue keyId = 1;</code>
     */
    public Builder clearKeyId() {
      if (keyIdBuilder_ == null) {
        keyId_ = null;
        onChanged();
      } else {
        keyId_ = null;
        keyIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue keyId = 1;</code>
     */
    public com.google.protobuf.StringValue.Builder getKeyIdBuilder() {
      
      onChanged();
      return getKeyIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue keyId = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getKeyIdOrBuilder() {
      if (keyIdBuilder_ != null) {
        return keyIdBuilder_.getMessageOrBuilder();
      } else {
        return keyId_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : keyId_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue keyId = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getKeyIdFieldBuilder() {
      if (keyIdBuilder_ == null) {
        keyIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getKeyId(),
                getParentForChildren(),
                isClean());
        keyId_ = null;
      }
      return keyIdBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:b.gateway.v1.KEKId)
  }

  // @@protoc_insertion_point(class_scope:b.gateway.v1.KEKId)
  private static final com.bbva.business.gateway.iso20022.KEKId DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bbva.business.gateway.iso20022.KEKId();
  }

  public static com.bbva.business.gateway.iso20022.KEKId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KEKId>
      PARSER = new com.google.protobuf.AbstractParser<KEKId>() {
    @java.lang.Override
    public KEKId parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KEKId(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KEKId> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KEKId> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bbva.business.gateway.iso20022.KEKId getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

