// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

public interface LoyaltyProgrammeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.LoyaltyProgramme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue programmeType = 1;</code>
   */
  boolean hasProgrammeType();
  /**
   * <code>.google.protobuf.StringValue programmeType = 1;</code>
   */
  com.google.protobuf.StringValue getProgrammeType();
  /**
   * <code>.google.protobuf.StringValue programmeType = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getProgrammeTypeOrBuilder();

  /**
   * <code>.google.protobuf.StringValue programmeId = 2;</code>
   */
  boolean hasProgrammeId();
  /**
   * <code>.google.protobuf.StringValue programmeId = 2;</code>
   */
  com.google.protobuf.StringValue getProgrammeId();
  /**
   * <code>.google.protobuf.StringValue programmeId = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getProgrammeIdOrBuilder();
}
