// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

/**
 * Protobuf type {@code b.gateway.v1.LoyaltyProgramme}
 */
public  final class LoyaltyProgramme extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:b.gateway.v1.LoyaltyProgramme)
    LoyaltyProgrammeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LoyaltyProgramme.newBuilder() to construct.
  private LoyaltyProgramme(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LoyaltyProgramme() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LoyaltyProgramme(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (programmeType_ != null) {
              subBuilder = programmeType_.toBuilder();
            }
            programmeType_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(programmeType_);
              programmeType_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (programmeId_ != null) {
              subBuilder = programmeId_.toBuilder();
            }
            programmeId_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(programmeId_);
              programmeId_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_LoyaltyProgramme_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_LoyaltyProgramme_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bbva.business.gateway.iso20022.LoyaltyProgramme.class, com.bbva.business.gateway.iso20022.LoyaltyProgramme.Builder.class);
  }

  public static final int PROGRAMMETYPE_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue programmeType_;
  /**
   * <code>.google.protobuf.StringValue programmeType = 1;</code>
   */
  public boolean hasProgrammeType() {
    return programmeType_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue programmeType = 1;</code>
   */
  public com.google.protobuf.StringValue getProgrammeType() {
    return programmeType_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : programmeType_;
  }
  /**
   * <code>.google.protobuf.StringValue programmeType = 1;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getProgrammeTypeOrBuilder() {
    return getProgrammeType();
  }

  public static final int PROGRAMMEID_FIELD_NUMBER = 2;
  private com.google.protobuf.StringValue programmeId_;
  /**
   * <code>.google.protobuf.StringValue programmeId = 2;</code>
   */
  public boolean hasProgrammeId() {
    return programmeId_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue programmeId = 2;</code>
   */
  public com.google.protobuf.StringValue getProgrammeId() {
    return programmeId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : programmeId_;
  }
  /**
   * <code>.google.protobuf.StringValue programmeId = 2;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getProgrammeIdOrBuilder() {
    return getProgrammeId();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (programmeType_ != null) {
      output.writeMessage(1, getProgrammeType());
    }
    if (programmeId_ != null) {
      output.writeMessage(2, getProgrammeId());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (programmeType_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getProgrammeType());
    }
    if (programmeId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getProgrammeId());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bbva.business.gateway.iso20022.LoyaltyProgramme)) {
      return super.equals(obj);
    }
    com.bbva.business.gateway.iso20022.LoyaltyProgramme other = (com.bbva.business.gateway.iso20022.LoyaltyProgramme) obj;

    boolean result = true;
    result = result && (hasProgrammeType() == other.hasProgrammeType());
    if (hasProgrammeType()) {
      result = result && getProgrammeType()
          .equals(other.getProgrammeType());
    }
    result = result && (hasProgrammeId() == other.hasProgrammeId());
    if (hasProgrammeId()) {
      result = result && getProgrammeId()
          .equals(other.getProgrammeId());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProgrammeType()) {
      hash = (37 * hash) + PROGRAMMETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getProgrammeType().hashCode();
    }
    if (hasProgrammeId()) {
      hash = (37 * hash) + PROGRAMMEID_FIELD_NUMBER;
      hash = (53 * hash) + getProgrammeId().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bbva.business.gateway.iso20022.LoyaltyProgramme parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.LoyaltyProgramme parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.LoyaltyProgramme parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.LoyaltyProgramme parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.LoyaltyProgramme parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.LoyaltyProgramme parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.LoyaltyProgramme parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.LoyaltyProgramme parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.LoyaltyProgramme parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.LoyaltyProgramme parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.LoyaltyProgramme parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.LoyaltyProgramme parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bbva.business.gateway.iso20022.LoyaltyProgramme prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code b.gateway.v1.LoyaltyProgramme}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:b.gateway.v1.LoyaltyProgramme)
      com.bbva.business.gateway.iso20022.LoyaltyProgrammeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_LoyaltyProgramme_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_LoyaltyProgramme_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbva.business.gateway.iso20022.LoyaltyProgramme.class, com.bbva.business.gateway.iso20022.LoyaltyProgramme.Builder.class);
    }

    // Construct using com.bbva.business.gateway.iso20022.LoyaltyProgramme.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (programmeTypeBuilder_ == null) {
        programmeType_ = null;
      } else {
        programmeType_ = null;
        programmeTypeBuilder_ = null;
      }
      if (programmeIdBuilder_ == null) {
        programmeId_ = null;
      } else {
        programmeId_ = null;
        programmeIdBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_LoyaltyProgramme_descriptor;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.LoyaltyProgramme getDefaultInstanceForType() {
      return com.bbva.business.gateway.iso20022.LoyaltyProgramme.getDefaultInstance();
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.LoyaltyProgramme build() {
      com.bbva.business.gateway.iso20022.LoyaltyProgramme result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.LoyaltyProgramme buildPartial() {
      com.bbva.business.gateway.iso20022.LoyaltyProgramme result = new com.bbva.business.gateway.iso20022.LoyaltyProgramme(this);
      if (programmeTypeBuilder_ == null) {
        result.programmeType_ = programmeType_;
      } else {
        result.programmeType_ = programmeTypeBuilder_.build();
      }
      if (programmeIdBuilder_ == null) {
        result.programmeId_ = programmeId_;
      } else {
        result.programmeId_ = programmeIdBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bbva.business.gateway.iso20022.LoyaltyProgramme) {
        return mergeFrom((com.bbva.business.gateway.iso20022.LoyaltyProgramme)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bbva.business.gateway.iso20022.LoyaltyProgramme other) {
      if (other == com.bbva.business.gateway.iso20022.LoyaltyProgramme.getDefaultInstance()) return this;
      if (other.hasProgrammeType()) {
        mergeProgrammeType(other.getProgrammeType());
      }
      if (other.hasProgrammeId()) {
        mergeProgrammeId(other.getProgrammeId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bbva.business.gateway.iso20022.LoyaltyProgramme parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bbva.business.gateway.iso20022.LoyaltyProgramme) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.StringValue programmeType_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> programmeTypeBuilder_;
    /**
     * <code>.google.protobuf.StringValue programmeType = 1;</code>
     */
    public boolean hasProgrammeType() {
      return programmeTypeBuilder_ != null || programmeType_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue programmeType = 1;</code>
     */
    public com.google.protobuf.StringValue getProgrammeType() {
      if (programmeTypeBuilder_ == null) {
        return programmeType_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : programmeType_;
      } else {
        return programmeTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue programmeType = 1;</code>
     */
    public Builder setProgrammeType(com.google.protobuf.StringValue value) {
      if (programmeTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        programmeType_ = value;
        onChanged();
      } else {
        programmeTypeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue programmeType = 1;</code>
     */
    public Builder setProgrammeType(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (programmeTypeBuilder_ == null) {
        programmeType_ = builderForValue.build();
        onChanged();
      } else {
        programmeTypeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue programmeType = 1;</code>
     */
    public Builder mergeProgrammeType(com.google.protobuf.StringValue value) {
      if (programmeTypeBuilder_ == null) {
        if (programmeType_ != null) {
          programmeType_ =
            com.google.protobuf.StringValue.newBuilder(programmeType_).mergeFrom(value).buildPartial();
        } else {
          programmeType_ = value;
        }
        onChanged();
      } else {
        programmeTypeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue programmeType = 1;</code>
     */
    public Builder clearProgrammeType() {
      if (programmeTypeBuilder_ == null) {
        programmeType_ = null;
        onChanged();
      } else {
        programmeType_ = null;
        programmeTypeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue programmeType = 1;</code>
     */
    public com.google.protobuf.StringValue.Builder getProgrammeTypeBuilder() {
      
      onChanged();
      return getProgrammeTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue programmeType = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getProgrammeTypeOrBuilder() {
      if (programmeTypeBuilder_ != null) {
        return programmeTypeBuilder_.getMessageOrBuilder();
      } else {
        return programmeType_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : programmeType_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue programmeType = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getProgrammeTypeFieldBuilder() {
      if (programmeTypeBuilder_ == null) {
        programmeTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getProgrammeType(),
                getParentForChildren(),
                isClean());
        programmeType_ = null;
      }
      return programmeTypeBuilder_;
    }

    private com.google.protobuf.StringValue programmeId_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> programmeIdBuilder_;
    /**
     * <code>.google.protobuf.StringValue programmeId = 2;</code>
     */
    public boolean hasProgrammeId() {
      return programmeIdBuilder_ != null || programmeId_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue programmeId = 2;</code>
     */
    public com.google.protobuf.StringValue getProgrammeId() {
      if (programmeIdBuilder_ == null) {
        return programmeId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : programmeId_;
      } else {
        return programmeIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue programmeId = 2;</code>
     */
    public Builder setProgrammeId(com.google.protobuf.StringValue value) {
      if (programmeIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        programmeId_ = value;
        onChanged();
      } else {
        programmeIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue programmeId = 2;</code>
     */
    public Builder setProgrammeId(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (programmeIdBuilder_ == null) {
        programmeId_ = builderForValue.build();
        onChanged();
      } else {
        programmeIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue programmeId = 2;</code>
     */
    public Builder mergeProgrammeId(com.google.protobuf.StringValue value) {
      if (programmeIdBuilder_ == null) {
        if (programmeId_ != null) {
          programmeId_ =
            com.google.protobuf.StringValue.newBuilder(programmeId_).mergeFrom(value).buildPartial();
        } else {
          programmeId_ = value;
        }
        onChanged();
      } else {
        programmeIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue programmeId = 2;</code>
     */
    public Builder clearProgrammeId() {
      if (programmeIdBuilder_ == null) {
        programmeId_ = null;
        onChanged();
      } else {
        programmeId_ = null;
        programmeIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue programmeId = 2;</code>
     */
    public com.google.protobuf.StringValue.Builder getProgrammeIdBuilder() {
      
      onChanged();
      return getProgrammeIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue programmeId = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getProgrammeIdOrBuilder() {
      if (programmeIdBuilder_ != null) {
        return programmeIdBuilder_.getMessageOrBuilder();
      } else {
        return programmeId_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : programmeId_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue programmeId = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getProgrammeIdFieldBuilder() {
      if (programmeIdBuilder_ == null) {
        programmeIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getProgrammeId(),
                getParentForChildren(),
                isClean());
        programmeId_ = null;
      }
      return programmeIdBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:b.gateway.v1.LoyaltyProgramme)
  }

  // @@protoc_insertion_point(class_scope:b.gateway.v1.LoyaltyProgramme)
  private static final com.bbva.business.gateway.iso20022.LoyaltyProgramme DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bbva.business.gateway.iso20022.LoyaltyProgramme();
  }

  public static com.bbva.business.gateway.iso20022.LoyaltyProgramme getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoyaltyProgramme>
      PARSER = new com.google.protobuf.AbstractParser<LoyaltyProgramme>() {
    @java.lang.Override
    public LoyaltyProgramme parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LoyaltyProgramme(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LoyaltyProgramme> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoyaltyProgramme> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bbva.business.gateway.iso20022.LoyaltyProgramme getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

