// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

/**
 * Protobuf type {@code b.gateway.v1.OriginalTransactionAmounts}
 */
public  final class OriginalTransactionAmounts extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:b.gateway.v1.OriginalTransactionAmounts)
    OriginalTransactionAmountsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OriginalTransactionAmounts.newBuilder() to construct.
  private OriginalTransactionAmounts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OriginalTransactionAmounts() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OriginalTransactionAmounts(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.bbva.business.gateway.iso20022.TransactionAmount.Builder subBuilder = null;
            if (transactionAmount_ != null) {
              subBuilder = transactionAmount_.toBuilder();
            }
            transactionAmount_ = input.readMessage(com.bbva.business.gateway.iso20022.TransactionAmount.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(transactionAmount_);
              transactionAmount_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.bbva.business.gateway.iso20022.CardholderBillingAmount.Builder subBuilder = null;
            if (cardholderBillingAmount_ != null) {
              subBuilder = cardholderBillingAmount_.toBuilder();
            }
            cardholderBillingAmount_ = input.readMessage(com.bbva.business.gateway.iso20022.CardholderBillingAmount.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cardholderBillingAmount_);
              cardholderBillingAmount_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.bbva.business.gateway.iso20022.ReconciliationAmount.Builder subBuilder = null;
            if (reconciliationAmount_ != null) {
              subBuilder = reconciliationAmount_.toBuilder();
            }
            reconciliationAmount_ = input.readMessage(com.bbva.business.gateway.iso20022.ReconciliationAmount.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(reconciliationAmount_);
              reconciliationAmount_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_OriginalTransactionAmounts_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_OriginalTransactionAmounts_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bbva.business.gateway.iso20022.OriginalTransactionAmounts.class, com.bbva.business.gateway.iso20022.OriginalTransactionAmounts.Builder.class);
  }

  public static final int TRANSACTIONAMOUNT_FIELD_NUMBER = 1;
  private com.bbva.business.gateway.iso20022.TransactionAmount transactionAmount_;
  /**
   * <code>.b.gateway.v1.TransactionAmount transactionAmount = 1;</code>
   */
  public boolean hasTransactionAmount() {
    return transactionAmount_ != null;
  }
  /**
   * <code>.b.gateway.v1.TransactionAmount transactionAmount = 1;</code>
   */
  public com.bbva.business.gateway.iso20022.TransactionAmount getTransactionAmount() {
    return transactionAmount_ == null ? com.bbva.business.gateway.iso20022.TransactionAmount.getDefaultInstance() : transactionAmount_;
  }
  /**
   * <code>.b.gateway.v1.TransactionAmount transactionAmount = 1;</code>
   */
  public com.bbva.business.gateway.iso20022.TransactionAmountOrBuilder getTransactionAmountOrBuilder() {
    return getTransactionAmount();
  }

  public static final int CARDHOLDERBILLINGAMOUNT_FIELD_NUMBER = 2;
  private com.bbva.business.gateway.iso20022.CardholderBillingAmount cardholderBillingAmount_;
  /**
   * <code>.b.gateway.v1.CardholderBillingAmount cardholderBillingAmount = 2;</code>
   */
  public boolean hasCardholderBillingAmount() {
    return cardholderBillingAmount_ != null;
  }
  /**
   * <code>.b.gateway.v1.CardholderBillingAmount cardholderBillingAmount = 2;</code>
   */
  public com.bbva.business.gateway.iso20022.CardholderBillingAmount getCardholderBillingAmount() {
    return cardholderBillingAmount_ == null ? com.bbva.business.gateway.iso20022.CardholderBillingAmount.getDefaultInstance() : cardholderBillingAmount_;
  }
  /**
   * <code>.b.gateway.v1.CardholderBillingAmount cardholderBillingAmount = 2;</code>
   */
  public com.bbva.business.gateway.iso20022.CardholderBillingAmountOrBuilder getCardholderBillingAmountOrBuilder() {
    return getCardholderBillingAmount();
  }

  public static final int RECONCILIATIONAMOUNT_FIELD_NUMBER = 3;
  private com.bbva.business.gateway.iso20022.ReconciliationAmount reconciliationAmount_;
  /**
   * <code>.b.gateway.v1.ReconciliationAmount reconciliationAmount = 3;</code>
   */
  public boolean hasReconciliationAmount() {
    return reconciliationAmount_ != null;
  }
  /**
   * <code>.b.gateway.v1.ReconciliationAmount reconciliationAmount = 3;</code>
   */
  public com.bbva.business.gateway.iso20022.ReconciliationAmount getReconciliationAmount() {
    return reconciliationAmount_ == null ? com.bbva.business.gateway.iso20022.ReconciliationAmount.getDefaultInstance() : reconciliationAmount_;
  }
  /**
   * <code>.b.gateway.v1.ReconciliationAmount reconciliationAmount = 3;</code>
   */
  public com.bbva.business.gateway.iso20022.ReconciliationAmountOrBuilder getReconciliationAmountOrBuilder() {
    return getReconciliationAmount();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (transactionAmount_ != null) {
      output.writeMessage(1, getTransactionAmount());
    }
    if (cardholderBillingAmount_ != null) {
      output.writeMessage(2, getCardholderBillingAmount());
    }
    if (reconciliationAmount_ != null) {
      output.writeMessage(3, getReconciliationAmount());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (transactionAmount_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTransactionAmount());
    }
    if (cardholderBillingAmount_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCardholderBillingAmount());
    }
    if (reconciliationAmount_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getReconciliationAmount());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bbva.business.gateway.iso20022.OriginalTransactionAmounts)) {
      return super.equals(obj);
    }
    com.bbva.business.gateway.iso20022.OriginalTransactionAmounts other = (com.bbva.business.gateway.iso20022.OriginalTransactionAmounts) obj;

    boolean result = true;
    result = result && (hasTransactionAmount() == other.hasTransactionAmount());
    if (hasTransactionAmount()) {
      result = result && getTransactionAmount()
          .equals(other.getTransactionAmount());
    }
    result = result && (hasCardholderBillingAmount() == other.hasCardholderBillingAmount());
    if (hasCardholderBillingAmount()) {
      result = result && getCardholderBillingAmount()
          .equals(other.getCardholderBillingAmount());
    }
    result = result && (hasReconciliationAmount() == other.hasReconciliationAmount());
    if (hasReconciliationAmount()) {
      result = result && getReconciliationAmount()
          .equals(other.getReconciliationAmount());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTransactionAmount()) {
      hash = (37 * hash) + TRANSACTIONAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionAmount().hashCode();
    }
    if (hasCardholderBillingAmount()) {
      hash = (37 * hash) + CARDHOLDERBILLINGAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCardholderBillingAmount().hashCode();
    }
    if (hasReconciliationAmount()) {
      hash = (37 * hash) + RECONCILIATIONAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getReconciliationAmount().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bbva.business.gateway.iso20022.OriginalTransactionAmounts parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.OriginalTransactionAmounts parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.OriginalTransactionAmounts parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.OriginalTransactionAmounts parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.OriginalTransactionAmounts parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.OriginalTransactionAmounts parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.OriginalTransactionAmounts parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.OriginalTransactionAmounts parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.OriginalTransactionAmounts parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.OriginalTransactionAmounts parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.OriginalTransactionAmounts parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.OriginalTransactionAmounts parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bbva.business.gateway.iso20022.OriginalTransactionAmounts prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code b.gateway.v1.OriginalTransactionAmounts}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:b.gateway.v1.OriginalTransactionAmounts)
      com.bbva.business.gateway.iso20022.OriginalTransactionAmountsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_OriginalTransactionAmounts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_OriginalTransactionAmounts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbva.business.gateway.iso20022.OriginalTransactionAmounts.class, com.bbva.business.gateway.iso20022.OriginalTransactionAmounts.Builder.class);
    }

    // Construct using com.bbva.business.gateway.iso20022.OriginalTransactionAmounts.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (transactionAmountBuilder_ == null) {
        transactionAmount_ = null;
      } else {
        transactionAmount_ = null;
        transactionAmountBuilder_ = null;
      }
      if (cardholderBillingAmountBuilder_ == null) {
        cardholderBillingAmount_ = null;
      } else {
        cardholderBillingAmount_ = null;
        cardholderBillingAmountBuilder_ = null;
      }
      if (reconciliationAmountBuilder_ == null) {
        reconciliationAmount_ = null;
      } else {
        reconciliationAmount_ = null;
        reconciliationAmountBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_OriginalTransactionAmounts_descriptor;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.OriginalTransactionAmounts getDefaultInstanceForType() {
      return com.bbva.business.gateway.iso20022.OriginalTransactionAmounts.getDefaultInstance();
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.OriginalTransactionAmounts build() {
      com.bbva.business.gateway.iso20022.OriginalTransactionAmounts result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.OriginalTransactionAmounts buildPartial() {
      com.bbva.business.gateway.iso20022.OriginalTransactionAmounts result = new com.bbva.business.gateway.iso20022.OriginalTransactionAmounts(this);
      if (transactionAmountBuilder_ == null) {
        result.transactionAmount_ = transactionAmount_;
      } else {
        result.transactionAmount_ = transactionAmountBuilder_.build();
      }
      if (cardholderBillingAmountBuilder_ == null) {
        result.cardholderBillingAmount_ = cardholderBillingAmount_;
      } else {
        result.cardholderBillingAmount_ = cardholderBillingAmountBuilder_.build();
      }
      if (reconciliationAmountBuilder_ == null) {
        result.reconciliationAmount_ = reconciliationAmount_;
      } else {
        result.reconciliationAmount_ = reconciliationAmountBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bbva.business.gateway.iso20022.OriginalTransactionAmounts) {
        return mergeFrom((com.bbva.business.gateway.iso20022.OriginalTransactionAmounts)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bbva.business.gateway.iso20022.OriginalTransactionAmounts other) {
      if (other == com.bbva.business.gateway.iso20022.OriginalTransactionAmounts.getDefaultInstance()) return this;
      if (other.hasTransactionAmount()) {
        mergeTransactionAmount(other.getTransactionAmount());
      }
      if (other.hasCardholderBillingAmount()) {
        mergeCardholderBillingAmount(other.getCardholderBillingAmount());
      }
      if (other.hasReconciliationAmount()) {
        mergeReconciliationAmount(other.getReconciliationAmount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bbva.business.gateway.iso20022.OriginalTransactionAmounts parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bbva.business.gateway.iso20022.OriginalTransactionAmounts) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.bbva.business.gateway.iso20022.TransactionAmount transactionAmount_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bbva.business.gateway.iso20022.TransactionAmount, com.bbva.business.gateway.iso20022.TransactionAmount.Builder, com.bbva.business.gateway.iso20022.TransactionAmountOrBuilder> transactionAmountBuilder_;
    /**
     * <code>.b.gateway.v1.TransactionAmount transactionAmount = 1;</code>
     */
    public boolean hasTransactionAmount() {
      return transactionAmountBuilder_ != null || transactionAmount_ != null;
    }
    /**
     * <code>.b.gateway.v1.TransactionAmount transactionAmount = 1;</code>
     */
    public com.bbva.business.gateway.iso20022.TransactionAmount getTransactionAmount() {
      if (transactionAmountBuilder_ == null) {
        return transactionAmount_ == null ? com.bbva.business.gateway.iso20022.TransactionAmount.getDefaultInstance() : transactionAmount_;
      } else {
        return transactionAmountBuilder_.getMessage();
      }
    }
    /**
     * <code>.b.gateway.v1.TransactionAmount transactionAmount = 1;</code>
     */
    public Builder setTransactionAmount(com.bbva.business.gateway.iso20022.TransactionAmount value) {
      if (transactionAmountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        transactionAmount_ = value;
        onChanged();
      } else {
        transactionAmountBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.b.gateway.v1.TransactionAmount transactionAmount = 1;</code>
     */
    public Builder setTransactionAmount(
        com.bbva.business.gateway.iso20022.TransactionAmount.Builder builderForValue) {
      if (transactionAmountBuilder_ == null) {
        transactionAmount_ = builderForValue.build();
        onChanged();
      } else {
        transactionAmountBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.b.gateway.v1.TransactionAmount transactionAmount = 1;</code>
     */
    public Builder mergeTransactionAmount(com.bbva.business.gateway.iso20022.TransactionAmount value) {
      if (transactionAmountBuilder_ == null) {
        if (transactionAmount_ != null) {
          transactionAmount_ =
            com.bbva.business.gateway.iso20022.TransactionAmount.newBuilder(transactionAmount_).mergeFrom(value).buildPartial();
        } else {
          transactionAmount_ = value;
        }
        onChanged();
      } else {
        transactionAmountBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.b.gateway.v1.TransactionAmount transactionAmount = 1;</code>
     */
    public Builder clearTransactionAmount() {
      if (transactionAmountBuilder_ == null) {
        transactionAmount_ = null;
        onChanged();
      } else {
        transactionAmount_ = null;
        transactionAmountBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.b.gateway.v1.TransactionAmount transactionAmount = 1;</code>
     */
    public com.bbva.business.gateway.iso20022.TransactionAmount.Builder getTransactionAmountBuilder() {
      
      onChanged();
      return getTransactionAmountFieldBuilder().getBuilder();
    }
    /**
     * <code>.b.gateway.v1.TransactionAmount transactionAmount = 1;</code>
     */
    public com.bbva.business.gateway.iso20022.TransactionAmountOrBuilder getTransactionAmountOrBuilder() {
      if (transactionAmountBuilder_ != null) {
        return transactionAmountBuilder_.getMessageOrBuilder();
      } else {
        return transactionAmount_ == null ?
            com.bbva.business.gateway.iso20022.TransactionAmount.getDefaultInstance() : transactionAmount_;
      }
    }
    /**
     * <code>.b.gateway.v1.TransactionAmount transactionAmount = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bbva.business.gateway.iso20022.TransactionAmount, com.bbva.business.gateway.iso20022.TransactionAmount.Builder, com.bbva.business.gateway.iso20022.TransactionAmountOrBuilder> 
        getTransactionAmountFieldBuilder() {
      if (transactionAmountBuilder_ == null) {
        transactionAmountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bbva.business.gateway.iso20022.TransactionAmount, com.bbva.business.gateway.iso20022.TransactionAmount.Builder, com.bbva.business.gateway.iso20022.TransactionAmountOrBuilder>(
                getTransactionAmount(),
                getParentForChildren(),
                isClean());
        transactionAmount_ = null;
      }
      return transactionAmountBuilder_;
    }

    private com.bbva.business.gateway.iso20022.CardholderBillingAmount cardholderBillingAmount_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bbva.business.gateway.iso20022.CardholderBillingAmount, com.bbva.business.gateway.iso20022.CardholderBillingAmount.Builder, com.bbva.business.gateway.iso20022.CardholderBillingAmountOrBuilder> cardholderBillingAmountBuilder_;
    /**
     * <code>.b.gateway.v1.CardholderBillingAmount cardholderBillingAmount = 2;</code>
     */
    public boolean hasCardholderBillingAmount() {
      return cardholderBillingAmountBuilder_ != null || cardholderBillingAmount_ != null;
    }
    /**
     * <code>.b.gateway.v1.CardholderBillingAmount cardholderBillingAmount = 2;</code>
     */
    public com.bbva.business.gateway.iso20022.CardholderBillingAmount getCardholderBillingAmount() {
      if (cardholderBillingAmountBuilder_ == null) {
        return cardholderBillingAmount_ == null ? com.bbva.business.gateway.iso20022.CardholderBillingAmount.getDefaultInstance() : cardholderBillingAmount_;
      } else {
        return cardholderBillingAmountBuilder_.getMessage();
      }
    }
    /**
     * <code>.b.gateway.v1.CardholderBillingAmount cardholderBillingAmount = 2;</code>
     */
    public Builder setCardholderBillingAmount(com.bbva.business.gateway.iso20022.CardholderBillingAmount value) {
      if (cardholderBillingAmountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cardholderBillingAmount_ = value;
        onChanged();
      } else {
        cardholderBillingAmountBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.b.gateway.v1.CardholderBillingAmount cardholderBillingAmount = 2;</code>
     */
    public Builder setCardholderBillingAmount(
        com.bbva.business.gateway.iso20022.CardholderBillingAmount.Builder builderForValue) {
      if (cardholderBillingAmountBuilder_ == null) {
        cardholderBillingAmount_ = builderForValue.build();
        onChanged();
      } else {
        cardholderBillingAmountBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.b.gateway.v1.CardholderBillingAmount cardholderBillingAmount = 2;</code>
     */
    public Builder mergeCardholderBillingAmount(com.bbva.business.gateway.iso20022.CardholderBillingAmount value) {
      if (cardholderBillingAmountBuilder_ == null) {
        if (cardholderBillingAmount_ != null) {
          cardholderBillingAmount_ =
            com.bbva.business.gateway.iso20022.CardholderBillingAmount.newBuilder(cardholderBillingAmount_).mergeFrom(value).buildPartial();
        } else {
          cardholderBillingAmount_ = value;
        }
        onChanged();
      } else {
        cardholderBillingAmountBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.b.gateway.v1.CardholderBillingAmount cardholderBillingAmount = 2;</code>
     */
    public Builder clearCardholderBillingAmount() {
      if (cardholderBillingAmountBuilder_ == null) {
        cardholderBillingAmount_ = null;
        onChanged();
      } else {
        cardholderBillingAmount_ = null;
        cardholderBillingAmountBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.b.gateway.v1.CardholderBillingAmount cardholderBillingAmount = 2;</code>
     */
    public com.bbva.business.gateway.iso20022.CardholderBillingAmount.Builder getCardholderBillingAmountBuilder() {
      
      onChanged();
      return getCardholderBillingAmountFieldBuilder().getBuilder();
    }
    /**
     * <code>.b.gateway.v1.CardholderBillingAmount cardholderBillingAmount = 2;</code>
     */
    public com.bbva.business.gateway.iso20022.CardholderBillingAmountOrBuilder getCardholderBillingAmountOrBuilder() {
      if (cardholderBillingAmountBuilder_ != null) {
        return cardholderBillingAmountBuilder_.getMessageOrBuilder();
      } else {
        return cardholderBillingAmount_ == null ?
            com.bbva.business.gateway.iso20022.CardholderBillingAmount.getDefaultInstance() : cardholderBillingAmount_;
      }
    }
    /**
     * <code>.b.gateway.v1.CardholderBillingAmount cardholderBillingAmount = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bbva.business.gateway.iso20022.CardholderBillingAmount, com.bbva.business.gateway.iso20022.CardholderBillingAmount.Builder, com.bbva.business.gateway.iso20022.CardholderBillingAmountOrBuilder> 
        getCardholderBillingAmountFieldBuilder() {
      if (cardholderBillingAmountBuilder_ == null) {
        cardholderBillingAmountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bbva.business.gateway.iso20022.CardholderBillingAmount, com.bbva.business.gateway.iso20022.CardholderBillingAmount.Builder, com.bbva.business.gateway.iso20022.CardholderBillingAmountOrBuilder>(
                getCardholderBillingAmount(),
                getParentForChildren(),
                isClean());
        cardholderBillingAmount_ = null;
      }
      return cardholderBillingAmountBuilder_;
    }

    private com.bbva.business.gateway.iso20022.ReconciliationAmount reconciliationAmount_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bbva.business.gateway.iso20022.ReconciliationAmount, com.bbva.business.gateway.iso20022.ReconciliationAmount.Builder, com.bbva.business.gateway.iso20022.ReconciliationAmountOrBuilder> reconciliationAmountBuilder_;
    /**
     * <code>.b.gateway.v1.ReconciliationAmount reconciliationAmount = 3;</code>
     */
    public boolean hasReconciliationAmount() {
      return reconciliationAmountBuilder_ != null || reconciliationAmount_ != null;
    }
    /**
     * <code>.b.gateway.v1.ReconciliationAmount reconciliationAmount = 3;</code>
     */
    public com.bbva.business.gateway.iso20022.ReconciliationAmount getReconciliationAmount() {
      if (reconciliationAmountBuilder_ == null) {
        return reconciliationAmount_ == null ? com.bbva.business.gateway.iso20022.ReconciliationAmount.getDefaultInstance() : reconciliationAmount_;
      } else {
        return reconciliationAmountBuilder_.getMessage();
      }
    }
    /**
     * <code>.b.gateway.v1.ReconciliationAmount reconciliationAmount = 3;</code>
     */
    public Builder setReconciliationAmount(com.bbva.business.gateway.iso20022.ReconciliationAmount value) {
      if (reconciliationAmountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reconciliationAmount_ = value;
        onChanged();
      } else {
        reconciliationAmountBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.b.gateway.v1.ReconciliationAmount reconciliationAmount = 3;</code>
     */
    public Builder setReconciliationAmount(
        com.bbva.business.gateway.iso20022.ReconciliationAmount.Builder builderForValue) {
      if (reconciliationAmountBuilder_ == null) {
        reconciliationAmount_ = builderForValue.build();
        onChanged();
      } else {
        reconciliationAmountBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.b.gateway.v1.ReconciliationAmount reconciliationAmount = 3;</code>
     */
    public Builder mergeReconciliationAmount(com.bbva.business.gateway.iso20022.ReconciliationAmount value) {
      if (reconciliationAmountBuilder_ == null) {
        if (reconciliationAmount_ != null) {
          reconciliationAmount_ =
            com.bbva.business.gateway.iso20022.ReconciliationAmount.newBuilder(reconciliationAmount_).mergeFrom(value).buildPartial();
        } else {
          reconciliationAmount_ = value;
        }
        onChanged();
      } else {
        reconciliationAmountBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.b.gateway.v1.ReconciliationAmount reconciliationAmount = 3;</code>
     */
    public Builder clearReconciliationAmount() {
      if (reconciliationAmountBuilder_ == null) {
        reconciliationAmount_ = null;
        onChanged();
      } else {
        reconciliationAmount_ = null;
        reconciliationAmountBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.b.gateway.v1.ReconciliationAmount reconciliationAmount = 3;</code>
     */
    public com.bbva.business.gateway.iso20022.ReconciliationAmount.Builder getReconciliationAmountBuilder() {
      
      onChanged();
      return getReconciliationAmountFieldBuilder().getBuilder();
    }
    /**
     * <code>.b.gateway.v1.ReconciliationAmount reconciliationAmount = 3;</code>
     */
    public com.bbva.business.gateway.iso20022.ReconciliationAmountOrBuilder getReconciliationAmountOrBuilder() {
      if (reconciliationAmountBuilder_ != null) {
        return reconciliationAmountBuilder_.getMessageOrBuilder();
      } else {
        return reconciliationAmount_ == null ?
            com.bbva.business.gateway.iso20022.ReconciliationAmount.getDefaultInstance() : reconciliationAmount_;
      }
    }
    /**
     * <code>.b.gateway.v1.ReconciliationAmount reconciliationAmount = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bbva.business.gateway.iso20022.ReconciliationAmount, com.bbva.business.gateway.iso20022.ReconciliationAmount.Builder, com.bbva.business.gateway.iso20022.ReconciliationAmountOrBuilder> 
        getReconciliationAmountFieldBuilder() {
      if (reconciliationAmountBuilder_ == null) {
        reconciliationAmountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bbva.business.gateway.iso20022.ReconciliationAmount, com.bbva.business.gateway.iso20022.ReconciliationAmount.Builder, com.bbva.business.gateway.iso20022.ReconciliationAmountOrBuilder>(
                getReconciliationAmount(),
                getParentForChildren(),
                isClean());
        reconciliationAmount_ = null;
      }
      return reconciliationAmountBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:b.gateway.v1.OriginalTransactionAmounts)
  }

  // @@protoc_insertion_point(class_scope:b.gateway.v1.OriginalTransactionAmounts)
  private static final com.bbva.business.gateway.iso20022.OriginalTransactionAmounts DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bbva.business.gateway.iso20022.OriginalTransactionAmounts();
  }

  public static com.bbva.business.gateway.iso20022.OriginalTransactionAmounts getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OriginalTransactionAmounts>
      PARSER = new com.google.protobuf.AbstractParser<OriginalTransactionAmounts>() {
    @java.lang.Override
    public OriginalTransactionAmounts parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OriginalTransactionAmounts(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OriginalTransactionAmounts> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OriginalTransactionAmounts> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bbva.business.gateway.iso20022.OriginalTransactionAmounts getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

