// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

public interface PoiComponentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.PoiComponent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.b.gateway.v1.Identification identification = 1;</code>
   */
  boolean hasIdentification();
  /**
   * <code>.b.gateway.v1.Identification identification = 1;</code>
   */
  com.bbva.business.gateway.iso20022.Identification getIdentification();
  /**
   * <code>.b.gateway.v1.Identification identification = 1;</code>
   */
  com.bbva.business.gateway.iso20022.IdentificationOrBuilder getIdentificationOrBuilder();

  /**
   * <code>repeated .b.gateway.v1.Assessment assessment = 2;</code>
   */
  java.util.List<com.bbva.business.gateway.iso20022.Assessment> 
      getAssessmentList();
  /**
   * <code>repeated .b.gateway.v1.Assessment assessment = 2;</code>
   */
  com.bbva.business.gateway.iso20022.Assessment getAssessment(int index);
  /**
   * <code>repeated .b.gateway.v1.Assessment assessment = 2;</code>
   */
  int getAssessmentCount();
  /**
   * <code>repeated .b.gateway.v1.Assessment assessment = 2;</code>
   */
  java.util.List<? extends com.bbva.business.gateway.iso20022.AssessmentOrBuilder> 
      getAssessmentOrBuilderList();
  /**
   * <code>repeated .b.gateway.v1.Assessment assessment = 2;</code>
   */
  com.bbva.business.gateway.iso20022.AssessmentOrBuilder getAssessmentOrBuilder(
      int index);
}
