// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

public interface PointOfServiceContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.PointOfServiceContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
   */
  boolean hasCardDataEntryMode();
  /**
   * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
   */
  com.google.protobuf.StringValue getCardDataEntryMode();
  /**
   * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getCardDataEntryModeOrBuilder();

  /**
   * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
   */
  boolean hasOtherCardDataEntryMode();
  /**
   * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
   */
  com.google.protobuf.StringValue getOtherCardDataEntryMode();
  /**
   * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getOtherCardDataEntryModeOrBuilder();

  /**
   * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
   */
  boolean hasCardPresent();
  /**
   * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
   */
  com.google.protobuf.BoolValue getCardPresent();
  /**
   * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getCardPresentOrBuilder();

  /**
   * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
   */
  boolean hasCardholderPresent();
  /**
   * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
   */
  com.google.protobuf.BoolValue getCardholderPresent();
  /**
   * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getCardholderPresentOrBuilder();

  /**
   * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
   */
  boolean hasUnattendedLevelCategory();
  /**
   * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
   */
  com.google.protobuf.StringValue getUnattendedLevelCategory();
  /**
   * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
   */
  com.google.protobuf.StringValueOrBuilder getUnattendedLevelCategoryOrBuilder();

  /**
   * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
   */
  boolean hasPartialApprovalSupported();
  /**
   * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
   */
  com.google.protobuf.BoolValue getPartialApprovalSupported();
  /**
   * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getPartialApprovalSupportedOrBuilder();

  /**
   * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
   */
  boolean hasOtherSecurityCharacteristics();
  /**
   * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
   */
  com.google.protobuf.StringValue getOtherSecurityCharacteristics();
  /**
   * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
   */
  com.google.protobuf.StringValueOrBuilder getOtherSecurityCharacteristicsOrBuilder();

  /**
   * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
   */
  boolean hasECommerceIndicator();
  /**
   * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
   */
  com.google.protobuf.BoolValue getECommerceIndicator();
  /**
   * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getECommerceIndicatorOrBuilder();

  /**
   * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
   */
  boolean hasMOTOCode();
  /**
   * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
   */
  com.google.protobuf.StringValue getMOTOCode();
  /**
   * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
   */
  com.google.protobuf.StringValueOrBuilder getMOTOCodeOrBuilder();

  /**
   * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
   */
  boolean hasAttendedIndicator();
  /**
   * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
   */
  com.google.protobuf.BoolValue getAttendedIndicator();
  /**
   * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getAttendedIndicatorOrBuilder();

  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
   */
  java.util.List<com.bbva.business.gateway.iso20022.AdditionalData> 
      getAdditionalDataList();
  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
   */
  com.bbva.business.gateway.iso20022.AdditionalData getAdditionalData(int index);
  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
   */
  int getAdditionalDataCount();
  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
   */
  java.util.List<? extends com.bbva.business.gateway.iso20022.AdditionalDataOrBuilder> 
      getAdditionalDataOrBuilderList();
  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
   */
  com.bbva.business.gateway.iso20022.AdditionalDataOrBuilder getAdditionalDataOrBuilder(
      int index);
}
