// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

/**
 * Protobuf type {@code b.gateway.v1.PointOfServiceContext}
 */
public  final class PointOfServiceContext extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:b.gateway.v1.PointOfServiceContext)
    PointOfServiceContextOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PointOfServiceContext.newBuilder() to construct.
  private PointOfServiceContext(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PointOfServiceContext() {
    additionalData_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PointOfServiceContext(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (cardDataEntryMode_ != null) {
              subBuilder = cardDataEntryMode_.toBuilder();
            }
            cardDataEntryMode_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cardDataEntryMode_);
              cardDataEntryMode_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (otherCardDataEntryMode_ != null) {
              subBuilder = otherCardDataEntryMode_.toBuilder();
            }
            otherCardDataEntryMode_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(otherCardDataEntryMode_);
              otherCardDataEntryMode_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.BoolValue.Builder subBuilder = null;
            if (cardPresent_ != null) {
              subBuilder = cardPresent_.toBuilder();
            }
            cardPresent_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cardPresent_);
              cardPresent_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.BoolValue.Builder subBuilder = null;
            if (cardholderPresent_ != null) {
              subBuilder = cardholderPresent_.toBuilder();
            }
            cardholderPresent_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cardholderPresent_);
              cardholderPresent_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (unattendedLevelCategory_ != null) {
              subBuilder = unattendedLevelCategory_.toBuilder();
            }
            unattendedLevelCategory_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(unattendedLevelCategory_);
              unattendedLevelCategory_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.protobuf.BoolValue.Builder subBuilder = null;
            if (partialApprovalSupported_ != null) {
              subBuilder = partialApprovalSupported_.toBuilder();
            }
            partialApprovalSupported_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(partialApprovalSupported_);
              partialApprovalSupported_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (otherSecurityCharacteristics_ != null) {
              subBuilder = otherSecurityCharacteristics_.toBuilder();
            }
            otherSecurityCharacteristics_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(otherSecurityCharacteristics_);
              otherSecurityCharacteristics_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.google.protobuf.BoolValue.Builder subBuilder = null;
            if (eCommerceIndicator_ != null) {
              subBuilder = eCommerceIndicator_.toBuilder();
            }
            eCommerceIndicator_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(eCommerceIndicator_);
              eCommerceIndicator_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (mOTOCode_ != null) {
              subBuilder = mOTOCode_.toBuilder();
            }
            mOTOCode_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(mOTOCode_);
              mOTOCode_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            com.google.protobuf.BoolValue.Builder subBuilder = null;
            if (attendedIndicator_ != null) {
              subBuilder = attendedIndicator_.toBuilder();
            }
            attendedIndicator_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(attendedIndicator_);
              attendedIndicator_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
              additionalData_ = new java.util.ArrayList<com.bbva.business.gateway.iso20022.AdditionalData>();
              mutable_bitField0_ |= 0x00000400;
            }
            additionalData_.add(
                input.readMessage(com.bbva.business.gateway.iso20022.AdditionalData.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
        additionalData_ = java.util.Collections.unmodifiableList(additionalData_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_PointOfServiceContext_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_PointOfServiceContext_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bbva.business.gateway.iso20022.PointOfServiceContext.class, com.bbva.business.gateway.iso20022.PointOfServiceContext.Builder.class);
  }

  private int bitField0_;
  public static final int CARDDATAENTRYMODE_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue cardDataEntryMode_;
  /**
   * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
   */
  public boolean hasCardDataEntryMode() {
    return cardDataEntryMode_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
   */
  public com.google.protobuf.StringValue getCardDataEntryMode() {
    return cardDataEntryMode_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : cardDataEntryMode_;
  }
  /**
   * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getCardDataEntryModeOrBuilder() {
    return getCardDataEntryMode();
  }

  public static final int OTHERCARDDATAENTRYMODE_FIELD_NUMBER = 2;
  private com.google.protobuf.StringValue otherCardDataEntryMode_;
  /**
   * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
   */
  public boolean hasOtherCardDataEntryMode() {
    return otherCardDataEntryMode_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
   */
  public com.google.protobuf.StringValue getOtherCardDataEntryMode() {
    return otherCardDataEntryMode_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : otherCardDataEntryMode_;
  }
  /**
   * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getOtherCardDataEntryModeOrBuilder() {
    return getOtherCardDataEntryMode();
  }

  public static final int CARDPRESENT_FIELD_NUMBER = 3;
  private com.google.protobuf.BoolValue cardPresent_;
  /**
   * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
   */
  public boolean hasCardPresent() {
    return cardPresent_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
   */
  public com.google.protobuf.BoolValue getCardPresent() {
    return cardPresent_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : cardPresent_;
  }
  /**
   * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
   */
  public com.google.protobuf.BoolValueOrBuilder getCardPresentOrBuilder() {
    return getCardPresent();
  }

  public static final int CARDHOLDERPRESENT_FIELD_NUMBER = 4;
  private com.google.protobuf.BoolValue cardholderPresent_;
  /**
   * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
   */
  public boolean hasCardholderPresent() {
    return cardholderPresent_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
   */
  public com.google.protobuf.BoolValue getCardholderPresent() {
    return cardholderPresent_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : cardholderPresent_;
  }
  /**
   * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
   */
  public com.google.protobuf.BoolValueOrBuilder getCardholderPresentOrBuilder() {
    return getCardholderPresent();
  }

  public static final int UNATTENDEDLEVELCATEGORY_FIELD_NUMBER = 5;
  private com.google.protobuf.StringValue unattendedLevelCategory_;
  /**
   * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
   */
  public boolean hasUnattendedLevelCategory() {
    return unattendedLevelCategory_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
   */
  public com.google.protobuf.StringValue getUnattendedLevelCategory() {
    return unattendedLevelCategory_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : unattendedLevelCategory_;
  }
  /**
   * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getUnattendedLevelCategoryOrBuilder() {
    return getUnattendedLevelCategory();
  }

  public static final int PARTIALAPPROVALSUPPORTED_FIELD_NUMBER = 6;
  private com.google.protobuf.BoolValue partialApprovalSupported_;
  /**
   * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
   */
  public boolean hasPartialApprovalSupported() {
    return partialApprovalSupported_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
   */
  public com.google.protobuf.BoolValue getPartialApprovalSupported() {
    return partialApprovalSupported_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : partialApprovalSupported_;
  }
  /**
   * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
   */
  public com.google.protobuf.BoolValueOrBuilder getPartialApprovalSupportedOrBuilder() {
    return getPartialApprovalSupported();
  }

  public static final int OTHERSECURITYCHARACTERISTICS_FIELD_NUMBER = 7;
  private com.google.protobuf.StringValue otherSecurityCharacteristics_;
  /**
   * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
   */
  public boolean hasOtherSecurityCharacteristics() {
    return otherSecurityCharacteristics_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
   */
  public com.google.protobuf.StringValue getOtherSecurityCharacteristics() {
    return otherSecurityCharacteristics_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : otherSecurityCharacteristics_;
  }
  /**
   * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getOtherSecurityCharacteristicsOrBuilder() {
    return getOtherSecurityCharacteristics();
  }

  public static final int ECOMMERCEINDICATOR_FIELD_NUMBER = 8;
  private com.google.protobuf.BoolValue eCommerceIndicator_;
  /**
   * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
   */
  public boolean hasECommerceIndicator() {
    return eCommerceIndicator_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
   */
  public com.google.protobuf.BoolValue getECommerceIndicator() {
    return eCommerceIndicator_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : eCommerceIndicator_;
  }
  /**
   * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
   */
  public com.google.protobuf.BoolValueOrBuilder getECommerceIndicatorOrBuilder() {
    return getECommerceIndicator();
  }

  public static final int MOTOCODE_FIELD_NUMBER = 9;
  private com.google.protobuf.StringValue mOTOCode_;
  /**
   * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
   */
  public boolean hasMOTOCode() {
    return mOTOCode_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
   */
  public com.google.protobuf.StringValue getMOTOCode() {
    return mOTOCode_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : mOTOCode_;
  }
  /**
   * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getMOTOCodeOrBuilder() {
    return getMOTOCode();
  }

  public static final int ATTENDEDINDICATOR_FIELD_NUMBER = 10;
  private com.google.protobuf.BoolValue attendedIndicator_;
  /**
   * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
   */
  public boolean hasAttendedIndicator() {
    return attendedIndicator_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
   */
  public com.google.protobuf.BoolValue getAttendedIndicator() {
    return attendedIndicator_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : attendedIndicator_;
  }
  /**
   * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
   */
  public com.google.protobuf.BoolValueOrBuilder getAttendedIndicatorOrBuilder() {
    return getAttendedIndicator();
  }

  public static final int ADDITIONALDATA_FIELD_NUMBER = 11;
  private java.util.List<com.bbva.business.gateway.iso20022.AdditionalData> additionalData_;
  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
   */
  public java.util.List<com.bbva.business.gateway.iso20022.AdditionalData> getAdditionalDataList() {
    return additionalData_;
  }
  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
   */
  public java.util.List<? extends com.bbva.business.gateway.iso20022.AdditionalDataOrBuilder> 
      getAdditionalDataOrBuilderList() {
    return additionalData_;
  }
  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
   */
  public int getAdditionalDataCount() {
    return additionalData_.size();
  }
  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
   */
  public com.bbva.business.gateway.iso20022.AdditionalData getAdditionalData(int index) {
    return additionalData_.get(index);
  }
  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
   */
  public com.bbva.business.gateway.iso20022.AdditionalDataOrBuilder getAdditionalDataOrBuilder(
      int index) {
    return additionalData_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cardDataEntryMode_ != null) {
      output.writeMessage(1, getCardDataEntryMode());
    }
    if (otherCardDataEntryMode_ != null) {
      output.writeMessage(2, getOtherCardDataEntryMode());
    }
    if (cardPresent_ != null) {
      output.writeMessage(3, getCardPresent());
    }
    if (cardholderPresent_ != null) {
      output.writeMessage(4, getCardholderPresent());
    }
    if (unattendedLevelCategory_ != null) {
      output.writeMessage(5, getUnattendedLevelCategory());
    }
    if (partialApprovalSupported_ != null) {
      output.writeMessage(6, getPartialApprovalSupported());
    }
    if (otherSecurityCharacteristics_ != null) {
      output.writeMessage(7, getOtherSecurityCharacteristics());
    }
    if (eCommerceIndicator_ != null) {
      output.writeMessage(8, getECommerceIndicator());
    }
    if (mOTOCode_ != null) {
      output.writeMessage(9, getMOTOCode());
    }
    if (attendedIndicator_ != null) {
      output.writeMessage(10, getAttendedIndicator());
    }
    for (int i = 0; i < additionalData_.size(); i++) {
      output.writeMessage(11, additionalData_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cardDataEntryMode_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCardDataEntryMode());
    }
    if (otherCardDataEntryMode_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOtherCardDataEntryMode());
    }
    if (cardPresent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getCardPresent());
    }
    if (cardholderPresent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCardholderPresent());
    }
    if (unattendedLevelCategory_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getUnattendedLevelCategory());
    }
    if (partialApprovalSupported_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getPartialApprovalSupported());
    }
    if (otherSecurityCharacteristics_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getOtherSecurityCharacteristics());
    }
    if (eCommerceIndicator_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getECommerceIndicator());
    }
    if (mOTOCode_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getMOTOCode());
    }
    if (attendedIndicator_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getAttendedIndicator());
    }
    for (int i = 0; i < additionalData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, additionalData_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bbva.business.gateway.iso20022.PointOfServiceContext)) {
      return super.equals(obj);
    }
    com.bbva.business.gateway.iso20022.PointOfServiceContext other = (com.bbva.business.gateway.iso20022.PointOfServiceContext) obj;

    boolean result = true;
    result = result && (hasCardDataEntryMode() == other.hasCardDataEntryMode());
    if (hasCardDataEntryMode()) {
      result = result && getCardDataEntryMode()
          .equals(other.getCardDataEntryMode());
    }
    result = result && (hasOtherCardDataEntryMode() == other.hasOtherCardDataEntryMode());
    if (hasOtherCardDataEntryMode()) {
      result = result && getOtherCardDataEntryMode()
          .equals(other.getOtherCardDataEntryMode());
    }
    result = result && (hasCardPresent() == other.hasCardPresent());
    if (hasCardPresent()) {
      result = result && getCardPresent()
          .equals(other.getCardPresent());
    }
    result = result && (hasCardholderPresent() == other.hasCardholderPresent());
    if (hasCardholderPresent()) {
      result = result && getCardholderPresent()
          .equals(other.getCardholderPresent());
    }
    result = result && (hasUnattendedLevelCategory() == other.hasUnattendedLevelCategory());
    if (hasUnattendedLevelCategory()) {
      result = result && getUnattendedLevelCategory()
          .equals(other.getUnattendedLevelCategory());
    }
    result = result && (hasPartialApprovalSupported() == other.hasPartialApprovalSupported());
    if (hasPartialApprovalSupported()) {
      result = result && getPartialApprovalSupported()
          .equals(other.getPartialApprovalSupported());
    }
    result = result && (hasOtherSecurityCharacteristics() == other.hasOtherSecurityCharacteristics());
    if (hasOtherSecurityCharacteristics()) {
      result = result && getOtherSecurityCharacteristics()
          .equals(other.getOtherSecurityCharacteristics());
    }
    result = result && (hasECommerceIndicator() == other.hasECommerceIndicator());
    if (hasECommerceIndicator()) {
      result = result && getECommerceIndicator()
          .equals(other.getECommerceIndicator());
    }
    result = result && (hasMOTOCode() == other.hasMOTOCode());
    if (hasMOTOCode()) {
      result = result && getMOTOCode()
          .equals(other.getMOTOCode());
    }
    result = result && (hasAttendedIndicator() == other.hasAttendedIndicator());
    if (hasAttendedIndicator()) {
      result = result && getAttendedIndicator()
          .equals(other.getAttendedIndicator());
    }
    result = result && getAdditionalDataList()
        .equals(other.getAdditionalDataList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCardDataEntryMode()) {
      hash = (37 * hash) + CARDDATAENTRYMODE_FIELD_NUMBER;
      hash = (53 * hash) + getCardDataEntryMode().hashCode();
    }
    if (hasOtherCardDataEntryMode()) {
      hash = (37 * hash) + OTHERCARDDATAENTRYMODE_FIELD_NUMBER;
      hash = (53 * hash) + getOtherCardDataEntryMode().hashCode();
    }
    if (hasCardPresent()) {
      hash = (37 * hash) + CARDPRESENT_FIELD_NUMBER;
      hash = (53 * hash) + getCardPresent().hashCode();
    }
    if (hasCardholderPresent()) {
      hash = (37 * hash) + CARDHOLDERPRESENT_FIELD_NUMBER;
      hash = (53 * hash) + getCardholderPresent().hashCode();
    }
    if (hasUnattendedLevelCategory()) {
      hash = (37 * hash) + UNATTENDEDLEVELCATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getUnattendedLevelCategory().hashCode();
    }
    if (hasPartialApprovalSupported()) {
      hash = (37 * hash) + PARTIALAPPROVALSUPPORTED_FIELD_NUMBER;
      hash = (53 * hash) + getPartialApprovalSupported().hashCode();
    }
    if (hasOtherSecurityCharacteristics()) {
      hash = (37 * hash) + OTHERSECURITYCHARACTERISTICS_FIELD_NUMBER;
      hash = (53 * hash) + getOtherSecurityCharacteristics().hashCode();
    }
    if (hasECommerceIndicator()) {
      hash = (37 * hash) + ECOMMERCEINDICATOR_FIELD_NUMBER;
      hash = (53 * hash) + getECommerceIndicator().hashCode();
    }
    if (hasMOTOCode()) {
      hash = (37 * hash) + MOTOCODE_FIELD_NUMBER;
      hash = (53 * hash) + getMOTOCode().hashCode();
    }
    if (hasAttendedIndicator()) {
      hash = (37 * hash) + ATTENDEDINDICATOR_FIELD_NUMBER;
      hash = (53 * hash) + getAttendedIndicator().hashCode();
    }
    if (getAdditionalDataCount() > 0) {
      hash = (37 * hash) + ADDITIONALDATA_FIELD_NUMBER;
      hash = (53 * hash) + getAdditionalDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bbva.business.gateway.iso20022.PointOfServiceContext parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.PointOfServiceContext parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.PointOfServiceContext parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.PointOfServiceContext parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.PointOfServiceContext parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.PointOfServiceContext parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.PointOfServiceContext parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.PointOfServiceContext parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.PointOfServiceContext parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.PointOfServiceContext parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.PointOfServiceContext parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.PointOfServiceContext parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bbva.business.gateway.iso20022.PointOfServiceContext prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code b.gateway.v1.PointOfServiceContext}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:b.gateway.v1.PointOfServiceContext)
      com.bbva.business.gateway.iso20022.PointOfServiceContextOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_PointOfServiceContext_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_PointOfServiceContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbva.business.gateway.iso20022.PointOfServiceContext.class, com.bbva.business.gateway.iso20022.PointOfServiceContext.Builder.class);
    }

    // Construct using com.bbva.business.gateway.iso20022.PointOfServiceContext.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAdditionalDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (cardDataEntryModeBuilder_ == null) {
        cardDataEntryMode_ = null;
      } else {
        cardDataEntryMode_ = null;
        cardDataEntryModeBuilder_ = null;
      }
      if (otherCardDataEntryModeBuilder_ == null) {
        otherCardDataEntryMode_ = null;
      } else {
        otherCardDataEntryMode_ = null;
        otherCardDataEntryModeBuilder_ = null;
      }
      if (cardPresentBuilder_ == null) {
        cardPresent_ = null;
      } else {
        cardPresent_ = null;
        cardPresentBuilder_ = null;
      }
      if (cardholderPresentBuilder_ == null) {
        cardholderPresent_ = null;
      } else {
        cardholderPresent_ = null;
        cardholderPresentBuilder_ = null;
      }
      if (unattendedLevelCategoryBuilder_ == null) {
        unattendedLevelCategory_ = null;
      } else {
        unattendedLevelCategory_ = null;
        unattendedLevelCategoryBuilder_ = null;
      }
      if (partialApprovalSupportedBuilder_ == null) {
        partialApprovalSupported_ = null;
      } else {
        partialApprovalSupported_ = null;
        partialApprovalSupportedBuilder_ = null;
      }
      if (otherSecurityCharacteristicsBuilder_ == null) {
        otherSecurityCharacteristics_ = null;
      } else {
        otherSecurityCharacteristics_ = null;
        otherSecurityCharacteristicsBuilder_ = null;
      }
      if (eCommerceIndicatorBuilder_ == null) {
        eCommerceIndicator_ = null;
      } else {
        eCommerceIndicator_ = null;
        eCommerceIndicatorBuilder_ = null;
      }
      if (mOTOCodeBuilder_ == null) {
        mOTOCode_ = null;
      } else {
        mOTOCode_ = null;
        mOTOCodeBuilder_ = null;
      }
      if (attendedIndicatorBuilder_ == null) {
        attendedIndicator_ = null;
      } else {
        attendedIndicator_ = null;
        attendedIndicatorBuilder_ = null;
      }
      if (additionalDataBuilder_ == null) {
        additionalData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000400);
      } else {
        additionalDataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_PointOfServiceContext_descriptor;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.PointOfServiceContext getDefaultInstanceForType() {
      return com.bbva.business.gateway.iso20022.PointOfServiceContext.getDefaultInstance();
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.PointOfServiceContext build() {
      com.bbva.business.gateway.iso20022.PointOfServiceContext result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.PointOfServiceContext buildPartial() {
      com.bbva.business.gateway.iso20022.PointOfServiceContext result = new com.bbva.business.gateway.iso20022.PointOfServiceContext(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (cardDataEntryModeBuilder_ == null) {
        result.cardDataEntryMode_ = cardDataEntryMode_;
      } else {
        result.cardDataEntryMode_ = cardDataEntryModeBuilder_.build();
      }
      if (otherCardDataEntryModeBuilder_ == null) {
        result.otherCardDataEntryMode_ = otherCardDataEntryMode_;
      } else {
        result.otherCardDataEntryMode_ = otherCardDataEntryModeBuilder_.build();
      }
      if (cardPresentBuilder_ == null) {
        result.cardPresent_ = cardPresent_;
      } else {
        result.cardPresent_ = cardPresentBuilder_.build();
      }
      if (cardholderPresentBuilder_ == null) {
        result.cardholderPresent_ = cardholderPresent_;
      } else {
        result.cardholderPresent_ = cardholderPresentBuilder_.build();
      }
      if (unattendedLevelCategoryBuilder_ == null) {
        result.unattendedLevelCategory_ = unattendedLevelCategory_;
      } else {
        result.unattendedLevelCategory_ = unattendedLevelCategoryBuilder_.build();
      }
      if (partialApprovalSupportedBuilder_ == null) {
        result.partialApprovalSupported_ = partialApprovalSupported_;
      } else {
        result.partialApprovalSupported_ = partialApprovalSupportedBuilder_.build();
      }
      if (otherSecurityCharacteristicsBuilder_ == null) {
        result.otherSecurityCharacteristics_ = otherSecurityCharacteristics_;
      } else {
        result.otherSecurityCharacteristics_ = otherSecurityCharacteristicsBuilder_.build();
      }
      if (eCommerceIndicatorBuilder_ == null) {
        result.eCommerceIndicator_ = eCommerceIndicator_;
      } else {
        result.eCommerceIndicator_ = eCommerceIndicatorBuilder_.build();
      }
      if (mOTOCodeBuilder_ == null) {
        result.mOTOCode_ = mOTOCode_;
      } else {
        result.mOTOCode_ = mOTOCodeBuilder_.build();
      }
      if (attendedIndicatorBuilder_ == null) {
        result.attendedIndicator_ = attendedIndicator_;
      } else {
        result.attendedIndicator_ = attendedIndicatorBuilder_.build();
      }
      if (additionalDataBuilder_ == null) {
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          additionalData_ = java.util.Collections.unmodifiableList(additionalData_);
          bitField0_ = (bitField0_ & ~0x00000400);
        }
        result.additionalData_ = additionalData_;
      } else {
        result.additionalData_ = additionalDataBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bbva.business.gateway.iso20022.PointOfServiceContext) {
        return mergeFrom((com.bbva.business.gateway.iso20022.PointOfServiceContext)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bbva.business.gateway.iso20022.PointOfServiceContext other) {
      if (other == com.bbva.business.gateway.iso20022.PointOfServiceContext.getDefaultInstance()) return this;
      if (other.hasCardDataEntryMode()) {
        mergeCardDataEntryMode(other.getCardDataEntryMode());
      }
      if (other.hasOtherCardDataEntryMode()) {
        mergeOtherCardDataEntryMode(other.getOtherCardDataEntryMode());
      }
      if (other.hasCardPresent()) {
        mergeCardPresent(other.getCardPresent());
      }
      if (other.hasCardholderPresent()) {
        mergeCardholderPresent(other.getCardholderPresent());
      }
      if (other.hasUnattendedLevelCategory()) {
        mergeUnattendedLevelCategory(other.getUnattendedLevelCategory());
      }
      if (other.hasPartialApprovalSupported()) {
        mergePartialApprovalSupported(other.getPartialApprovalSupported());
      }
      if (other.hasOtherSecurityCharacteristics()) {
        mergeOtherSecurityCharacteristics(other.getOtherSecurityCharacteristics());
      }
      if (other.hasECommerceIndicator()) {
        mergeECommerceIndicator(other.getECommerceIndicator());
      }
      if (other.hasMOTOCode()) {
        mergeMOTOCode(other.getMOTOCode());
      }
      if (other.hasAttendedIndicator()) {
        mergeAttendedIndicator(other.getAttendedIndicator());
      }
      if (additionalDataBuilder_ == null) {
        if (!other.additionalData_.isEmpty()) {
          if (additionalData_.isEmpty()) {
            additionalData_ = other.additionalData_;
            bitField0_ = (bitField0_ & ~0x00000400);
          } else {
            ensureAdditionalDataIsMutable();
            additionalData_.addAll(other.additionalData_);
          }
          onChanged();
        }
      } else {
        if (!other.additionalData_.isEmpty()) {
          if (additionalDataBuilder_.isEmpty()) {
            additionalDataBuilder_.dispose();
            additionalDataBuilder_ = null;
            additionalData_ = other.additionalData_;
            bitField0_ = (bitField0_ & ~0x00000400);
            additionalDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAdditionalDataFieldBuilder() : null;
          } else {
            additionalDataBuilder_.addAllMessages(other.additionalData_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bbva.business.gateway.iso20022.PointOfServiceContext parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bbva.business.gateway.iso20022.PointOfServiceContext) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.StringValue cardDataEntryMode_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> cardDataEntryModeBuilder_;
    /**
     * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
     */
    public boolean hasCardDataEntryMode() {
      return cardDataEntryModeBuilder_ != null || cardDataEntryMode_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
     */
    public com.google.protobuf.StringValue getCardDataEntryMode() {
      if (cardDataEntryModeBuilder_ == null) {
        return cardDataEntryMode_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : cardDataEntryMode_;
      } else {
        return cardDataEntryModeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
     */
    public Builder setCardDataEntryMode(com.google.protobuf.StringValue value) {
      if (cardDataEntryModeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cardDataEntryMode_ = value;
        onChanged();
      } else {
        cardDataEntryModeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
     */
    public Builder setCardDataEntryMode(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (cardDataEntryModeBuilder_ == null) {
        cardDataEntryMode_ = builderForValue.build();
        onChanged();
      } else {
        cardDataEntryModeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
     */
    public Builder mergeCardDataEntryMode(com.google.protobuf.StringValue value) {
      if (cardDataEntryModeBuilder_ == null) {
        if (cardDataEntryMode_ != null) {
          cardDataEntryMode_ =
            com.google.protobuf.StringValue.newBuilder(cardDataEntryMode_).mergeFrom(value).buildPartial();
        } else {
          cardDataEntryMode_ = value;
        }
        onChanged();
      } else {
        cardDataEntryModeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
     */
    public Builder clearCardDataEntryMode() {
      if (cardDataEntryModeBuilder_ == null) {
        cardDataEntryMode_ = null;
        onChanged();
      } else {
        cardDataEntryMode_ = null;
        cardDataEntryModeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
     */
    public com.google.protobuf.StringValue.Builder getCardDataEntryModeBuilder() {
      
      onChanged();
      return getCardDataEntryModeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getCardDataEntryModeOrBuilder() {
      if (cardDataEntryModeBuilder_ != null) {
        return cardDataEntryModeBuilder_.getMessageOrBuilder();
      } else {
        return cardDataEntryMode_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : cardDataEntryMode_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue cardDataEntryMode = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getCardDataEntryModeFieldBuilder() {
      if (cardDataEntryModeBuilder_ == null) {
        cardDataEntryModeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getCardDataEntryMode(),
                getParentForChildren(),
                isClean());
        cardDataEntryMode_ = null;
      }
      return cardDataEntryModeBuilder_;
    }

    private com.google.protobuf.StringValue otherCardDataEntryMode_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> otherCardDataEntryModeBuilder_;
    /**
     * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
     */
    public boolean hasOtherCardDataEntryMode() {
      return otherCardDataEntryModeBuilder_ != null || otherCardDataEntryMode_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
     */
    public com.google.protobuf.StringValue getOtherCardDataEntryMode() {
      if (otherCardDataEntryModeBuilder_ == null) {
        return otherCardDataEntryMode_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : otherCardDataEntryMode_;
      } else {
        return otherCardDataEntryModeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
     */
    public Builder setOtherCardDataEntryMode(com.google.protobuf.StringValue value) {
      if (otherCardDataEntryModeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        otherCardDataEntryMode_ = value;
        onChanged();
      } else {
        otherCardDataEntryModeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
     */
    public Builder setOtherCardDataEntryMode(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (otherCardDataEntryModeBuilder_ == null) {
        otherCardDataEntryMode_ = builderForValue.build();
        onChanged();
      } else {
        otherCardDataEntryModeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
     */
    public Builder mergeOtherCardDataEntryMode(com.google.protobuf.StringValue value) {
      if (otherCardDataEntryModeBuilder_ == null) {
        if (otherCardDataEntryMode_ != null) {
          otherCardDataEntryMode_ =
            com.google.protobuf.StringValue.newBuilder(otherCardDataEntryMode_).mergeFrom(value).buildPartial();
        } else {
          otherCardDataEntryMode_ = value;
        }
        onChanged();
      } else {
        otherCardDataEntryModeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
     */
    public Builder clearOtherCardDataEntryMode() {
      if (otherCardDataEntryModeBuilder_ == null) {
        otherCardDataEntryMode_ = null;
        onChanged();
      } else {
        otherCardDataEntryMode_ = null;
        otherCardDataEntryModeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
     */
    public com.google.protobuf.StringValue.Builder getOtherCardDataEntryModeBuilder() {
      
      onChanged();
      return getOtherCardDataEntryModeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getOtherCardDataEntryModeOrBuilder() {
      if (otherCardDataEntryModeBuilder_ != null) {
        return otherCardDataEntryModeBuilder_.getMessageOrBuilder();
      } else {
        return otherCardDataEntryMode_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : otherCardDataEntryMode_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue otherCardDataEntryMode = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getOtherCardDataEntryModeFieldBuilder() {
      if (otherCardDataEntryModeBuilder_ == null) {
        otherCardDataEntryModeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getOtherCardDataEntryMode(),
                getParentForChildren(),
                isClean());
        otherCardDataEntryMode_ = null;
      }
      return otherCardDataEntryModeBuilder_;
    }

    private com.google.protobuf.BoolValue cardPresent_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> cardPresentBuilder_;
    /**
     * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
     */
    public boolean hasCardPresent() {
      return cardPresentBuilder_ != null || cardPresent_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
     */
    public com.google.protobuf.BoolValue getCardPresent() {
      if (cardPresentBuilder_ == null) {
        return cardPresent_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : cardPresent_;
      } else {
        return cardPresentBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
     */
    public Builder setCardPresent(com.google.protobuf.BoolValue value) {
      if (cardPresentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cardPresent_ = value;
        onChanged();
      } else {
        cardPresentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
     */
    public Builder setCardPresent(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (cardPresentBuilder_ == null) {
        cardPresent_ = builderForValue.build();
        onChanged();
      } else {
        cardPresentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
     */
    public Builder mergeCardPresent(com.google.protobuf.BoolValue value) {
      if (cardPresentBuilder_ == null) {
        if (cardPresent_ != null) {
          cardPresent_ =
            com.google.protobuf.BoolValue.newBuilder(cardPresent_).mergeFrom(value).buildPartial();
        } else {
          cardPresent_ = value;
        }
        onChanged();
      } else {
        cardPresentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
     */
    public Builder clearCardPresent() {
      if (cardPresentBuilder_ == null) {
        cardPresent_ = null;
        onChanged();
      } else {
        cardPresent_ = null;
        cardPresentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
     */
    public com.google.protobuf.BoolValue.Builder getCardPresentBuilder() {
      
      onChanged();
      return getCardPresentFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getCardPresentOrBuilder() {
      if (cardPresentBuilder_ != null) {
        return cardPresentBuilder_.getMessageOrBuilder();
      } else {
        return cardPresent_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : cardPresent_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue cardPresent = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getCardPresentFieldBuilder() {
      if (cardPresentBuilder_ == null) {
        cardPresentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getCardPresent(),
                getParentForChildren(),
                isClean());
        cardPresent_ = null;
      }
      return cardPresentBuilder_;
    }

    private com.google.protobuf.BoolValue cardholderPresent_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> cardholderPresentBuilder_;
    /**
     * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
     */
    public boolean hasCardholderPresent() {
      return cardholderPresentBuilder_ != null || cardholderPresent_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
     */
    public com.google.protobuf.BoolValue getCardholderPresent() {
      if (cardholderPresentBuilder_ == null) {
        return cardholderPresent_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : cardholderPresent_;
      } else {
        return cardholderPresentBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
     */
    public Builder setCardholderPresent(com.google.protobuf.BoolValue value) {
      if (cardholderPresentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cardholderPresent_ = value;
        onChanged();
      } else {
        cardholderPresentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
     */
    public Builder setCardholderPresent(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (cardholderPresentBuilder_ == null) {
        cardholderPresent_ = builderForValue.build();
        onChanged();
      } else {
        cardholderPresentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
     */
    public Builder mergeCardholderPresent(com.google.protobuf.BoolValue value) {
      if (cardholderPresentBuilder_ == null) {
        if (cardholderPresent_ != null) {
          cardholderPresent_ =
            com.google.protobuf.BoolValue.newBuilder(cardholderPresent_).mergeFrom(value).buildPartial();
        } else {
          cardholderPresent_ = value;
        }
        onChanged();
      } else {
        cardholderPresentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
     */
    public Builder clearCardholderPresent() {
      if (cardholderPresentBuilder_ == null) {
        cardholderPresent_ = null;
        onChanged();
      } else {
        cardholderPresent_ = null;
        cardholderPresentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
     */
    public com.google.protobuf.BoolValue.Builder getCardholderPresentBuilder() {
      
      onChanged();
      return getCardholderPresentFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getCardholderPresentOrBuilder() {
      if (cardholderPresentBuilder_ != null) {
        return cardholderPresentBuilder_.getMessageOrBuilder();
      } else {
        return cardholderPresent_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : cardholderPresent_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue cardholderPresent = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getCardholderPresentFieldBuilder() {
      if (cardholderPresentBuilder_ == null) {
        cardholderPresentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getCardholderPresent(),
                getParentForChildren(),
                isClean());
        cardholderPresent_ = null;
      }
      return cardholderPresentBuilder_;
    }

    private com.google.protobuf.StringValue unattendedLevelCategory_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> unattendedLevelCategoryBuilder_;
    /**
     * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
     */
    public boolean hasUnattendedLevelCategory() {
      return unattendedLevelCategoryBuilder_ != null || unattendedLevelCategory_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
     */
    public com.google.protobuf.StringValue getUnattendedLevelCategory() {
      if (unattendedLevelCategoryBuilder_ == null) {
        return unattendedLevelCategory_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : unattendedLevelCategory_;
      } else {
        return unattendedLevelCategoryBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
     */
    public Builder setUnattendedLevelCategory(com.google.protobuf.StringValue value) {
      if (unattendedLevelCategoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unattendedLevelCategory_ = value;
        onChanged();
      } else {
        unattendedLevelCategoryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
     */
    public Builder setUnattendedLevelCategory(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (unattendedLevelCategoryBuilder_ == null) {
        unattendedLevelCategory_ = builderForValue.build();
        onChanged();
      } else {
        unattendedLevelCategoryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
     */
    public Builder mergeUnattendedLevelCategory(com.google.protobuf.StringValue value) {
      if (unattendedLevelCategoryBuilder_ == null) {
        if (unattendedLevelCategory_ != null) {
          unattendedLevelCategory_ =
            com.google.protobuf.StringValue.newBuilder(unattendedLevelCategory_).mergeFrom(value).buildPartial();
        } else {
          unattendedLevelCategory_ = value;
        }
        onChanged();
      } else {
        unattendedLevelCategoryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
     */
    public Builder clearUnattendedLevelCategory() {
      if (unattendedLevelCategoryBuilder_ == null) {
        unattendedLevelCategory_ = null;
        onChanged();
      } else {
        unattendedLevelCategory_ = null;
        unattendedLevelCategoryBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
     */
    public com.google.protobuf.StringValue.Builder getUnattendedLevelCategoryBuilder() {
      
      onChanged();
      return getUnattendedLevelCategoryFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getUnattendedLevelCategoryOrBuilder() {
      if (unattendedLevelCategoryBuilder_ != null) {
        return unattendedLevelCategoryBuilder_.getMessageOrBuilder();
      } else {
        return unattendedLevelCategory_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : unattendedLevelCategory_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue unattendedLevelCategory = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getUnattendedLevelCategoryFieldBuilder() {
      if (unattendedLevelCategoryBuilder_ == null) {
        unattendedLevelCategoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getUnattendedLevelCategory(),
                getParentForChildren(),
                isClean());
        unattendedLevelCategory_ = null;
      }
      return unattendedLevelCategoryBuilder_;
    }

    private com.google.protobuf.BoolValue partialApprovalSupported_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> partialApprovalSupportedBuilder_;
    /**
     * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
     */
    public boolean hasPartialApprovalSupported() {
      return partialApprovalSupportedBuilder_ != null || partialApprovalSupported_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
     */
    public com.google.protobuf.BoolValue getPartialApprovalSupported() {
      if (partialApprovalSupportedBuilder_ == null) {
        return partialApprovalSupported_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : partialApprovalSupported_;
      } else {
        return partialApprovalSupportedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
     */
    public Builder setPartialApprovalSupported(com.google.protobuf.BoolValue value) {
      if (partialApprovalSupportedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        partialApprovalSupported_ = value;
        onChanged();
      } else {
        partialApprovalSupportedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
     */
    public Builder setPartialApprovalSupported(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (partialApprovalSupportedBuilder_ == null) {
        partialApprovalSupported_ = builderForValue.build();
        onChanged();
      } else {
        partialApprovalSupportedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
     */
    public Builder mergePartialApprovalSupported(com.google.protobuf.BoolValue value) {
      if (partialApprovalSupportedBuilder_ == null) {
        if (partialApprovalSupported_ != null) {
          partialApprovalSupported_ =
            com.google.protobuf.BoolValue.newBuilder(partialApprovalSupported_).mergeFrom(value).buildPartial();
        } else {
          partialApprovalSupported_ = value;
        }
        onChanged();
      } else {
        partialApprovalSupportedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
     */
    public Builder clearPartialApprovalSupported() {
      if (partialApprovalSupportedBuilder_ == null) {
        partialApprovalSupported_ = null;
        onChanged();
      } else {
        partialApprovalSupported_ = null;
        partialApprovalSupportedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
     */
    public com.google.protobuf.BoolValue.Builder getPartialApprovalSupportedBuilder() {
      
      onChanged();
      return getPartialApprovalSupportedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getPartialApprovalSupportedOrBuilder() {
      if (partialApprovalSupportedBuilder_ != null) {
        return partialApprovalSupportedBuilder_.getMessageOrBuilder();
      } else {
        return partialApprovalSupported_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : partialApprovalSupported_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue partialApprovalSupported = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getPartialApprovalSupportedFieldBuilder() {
      if (partialApprovalSupportedBuilder_ == null) {
        partialApprovalSupportedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getPartialApprovalSupported(),
                getParentForChildren(),
                isClean());
        partialApprovalSupported_ = null;
      }
      return partialApprovalSupportedBuilder_;
    }

    private com.google.protobuf.StringValue otherSecurityCharacteristics_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> otherSecurityCharacteristicsBuilder_;
    /**
     * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
     */
    public boolean hasOtherSecurityCharacteristics() {
      return otherSecurityCharacteristicsBuilder_ != null || otherSecurityCharacteristics_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
     */
    public com.google.protobuf.StringValue getOtherSecurityCharacteristics() {
      if (otherSecurityCharacteristicsBuilder_ == null) {
        return otherSecurityCharacteristics_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : otherSecurityCharacteristics_;
      } else {
        return otherSecurityCharacteristicsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
     */
    public Builder setOtherSecurityCharacteristics(com.google.protobuf.StringValue value) {
      if (otherSecurityCharacteristicsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        otherSecurityCharacteristics_ = value;
        onChanged();
      } else {
        otherSecurityCharacteristicsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
     */
    public Builder setOtherSecurityCharacteristics(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (otherSecurityCharacteristicsBuilder_ == null) {
        otherSecurityCharacteristics_ = builderForValue.build();
        onChanged();
      } else {
        otherSecurityCharacteristicsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
     */
    public Builder mergeOtherSecurityCharacteristics(com.google.protobuf.StringValue value) {
      if (otherSecurityCharacteristicsBuilder_ == null) {
        if (otherSecurityCharacteristics_ != null) {
          otherSecurityCharacteristics_ =
            com.google.protobuf.StringValue.newBuilder(otherSecurityCharacteristics_).mergeFrom(value).buildPartial();
        } else {
          otherSecurityCharacteristics_ = value;
        }
        onChanged();
      } else {
        otherSecurityCharacteristicsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
     */
    public Builder clearOtherSecurityCharacteristics() {
      if (otherSecurityCharacteristicsBuilder_ == null) {
        otherSecurityCharacteristics_ = null;
        onChanged();
      } else {
        otherSecurityCharacteristics_ = null;
        otherSecurityCharacteristicsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
     */
    public com.google.protobuf.StringValue.Builder getOtherSecurityCharacteristicsBuilder() {
      
      onChanged();
      return getOtherSecurityCharacteristicsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getOtherSecurityCharacteristicsOrBuilder() {
      if (otherSecurityCharacteristicsBuilder_ != null) {
        return otherSecurityCharacteristicsBuilder_.getMessageOrBuilder();
      } else {
        return otherSecurityCharacteristics_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : otherSecurityCharacteristics_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue otherSecurityCharacteristics = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getOtherSecurityCharacteristicsFieldBuilder() {
      if (otherSecurityCharacteristicsBuilder_ == null) {
        otherSecurityCharacteristicsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getOtherSecurityCharacteristics(),
                getParentForChildren(),
                isClean());
        otherSecurityCharacteristics_ = null;
      }
      return otherSecurityCharacteristicsBuilder_;
    }

    private com.google.protobuf.BoolValue eCommerceIndicator_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> eCommerceIndicatorBuilder_;
    /**
     * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
     */
    public boolean hasECommerceIndicator() {
      return eCommerceIndicatorBuilder_ != null || eCommerceIndicator_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
     */
    public com.google.protobuf.BoolValue getECommerceIndicator() {
      if (eCommerceIndicatorBuilder_ == null) {
        return eCommerceIndicator_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : eCommerceIndicator_;
      } else {
        return eCommerceIndicatorBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
     */
    public Builder setECommerceIndicator(com.google.protobuf.BoolValue value) {
      if (eCommerceIndicatorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eCommerceIndicator_ = value;
        onChanged();
      } else {
        eCommerceIndicatorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
     */
    public Builder setECommerceIndicator(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (eCommerceIndicatorBuilder_ == null) {
        eCommerceIndicator_ = builderForValue.build();
        onChanged();
      } else {
        eCommerceIndicatorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
     */
    public Builder mergeECommerceIndicator(com.google.protobuf.BoolValue value) {
      if (eCommerceIndicatorBuilder_ == null) {
        if (eCommerceIndicator_ != null) {
          eCommerceIndicator_ =
            com.google.protobuf.BoolValue.newBuilder(eCommerceIndicator_).mergeFrom(value).buildPartial();
        } else {
          eCommerceIndicator_ = value;
        }
        onChanged();
      } else {
        eCommerceIndicatorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
     */
    public Builder clearECommerceIndicator() {
      if (eCommerceIndicatorBuilder_ == null) {
        eCommerceIndicator_ = null;
        onChanged();
      } else {
        eCommerceIndicator_ = null;
        eCommerceIndicatorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
     */
    public com.google.protobuf.BoolValue.Builder getECommerceIndicatorBuilder() {
      
      onChanged();
      return getECommerceIndicatorFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getECommerceIndicatorOrBuilder() {
      if (eCommerceIndicatorBuilder_ != null) {
        return eCommerceIndicatorBuilder_.getMessageOrBuilder();
      } else {
        return eCommerceIndicator_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : eCommerceIndicator_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue eCommerceIndicator = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getECommerceIndicatorFieldBuilder() {
      if (eCommerceIndicatorBuilder_ == null) {
        eCommerceIndicatorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getECommerceIndicator(),
                getParentForChildren(),
                isClean());
        eCommerceIndicator_ = null;
      }
      return eCommerceIndicatorBuilder_;
    }

    private com.google.protobuf.StringValue mOTOCode_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> mOTOCodeBuilder_;
    /**
     * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
     */
    public boolean hasMOTOCode() {
      return mOTOCodeBuilder_ != null || mOTOCode_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
     */
    public com.google.protobuf.StringValue getMOTOCode() {
      if (mOTOCodeBuilder_ == null) {
        return mOTOCode_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : mOTOCode_;
      } else {
        return mOTOCodeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
     */
    public Builder setMOTOCode(com.google.protobuf.StringValue value) {
      if (mOTOCodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mOTOCode_ = value;
        onChanged();
      } else {
        mOTOCodeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
     */
    public Builder setMOTOCode(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (mOTOCodeBuilder_ == null) {
        mOTOCode_ = builderForValue.build();
        onChanged();
      } else {
        mOTOCodeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
     */
    public Builder mergeMOTOCode(com.google.protobuf.StringValue value) {
      if (mOTOCodeBuilder_ == null) {
        if (mOTOCode_ != null) {
          mOTOCode_ =
            com.google.protobuf.StringValue.newBuilder(mOTOCode_).mergeFrom(value).buildPartial();
        } else {
          mOTOCode_ = value;
        }
        onChanged();
      } else {
        mOTOCodeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
     */
    public Builder clearMOTOCode() {
      if (mOTOCodeBuilder_ == null) {
        mOTOCode_ = null;
        onChanged();
      } else {
        mOTOCode_ = null;
        mOTOCodeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
     */
    public com.google.protobuf.StringValue.Builder getMOTOCodeBuilder() {
      
      onChanged();
      return getMOTOCodeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getMOTOCodeOrBuilder() {
      if (mOTOCodeBuilder_ != null) {
        return mOTOCodeBuilder_.getMessageOrBuilder();
      } else {
        return mOTOCode_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : mOTOCode_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue mOTOCode = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getMOTOCodeFieldBuilder() {
      if (mOTOCodeBuilder_ == null) {
        mOTOCodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getMOTOCode(),
                getParentForChildren(),
                isClean());
        mOTOCode_ = null;
      }
      return mOTOCodeBuilder_;
    }

    private com.google.protobuf.BoolValue attendedIndicator_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> attendedIndicatorBuilder_;
    /**
     * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
     */
    public boolean hasAttendedIndicator() {
      return attendedIndicatorBuilder_ != null || attendedIndicator_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
     */
    public com.google.protobuf.BoolValue getAttendedIndicator() {
      if (attendedIndicatorBuilder_ == null) {
        return attendedIndicator_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : attendedIndicator_;
      } else {
        return attendedIndicatorBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
     */
    public Builder setAttendedIndicator(com.google.protobuf.BoolValue value) {
      if (attendedIndicatorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        attendedIndicator_ = value;
        onChanged();
      } else {
        attendedIndicatorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
     */
    public Builder setAttendedIndicator(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (attendedIndicatorBuilder_ == null) {
        attendedIndicator_ = builderForValue.build();
        onChanged();
      } else {
        attendedIndicatorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
     */
    public Builder mergeAttendedIndicator(com.google.protobuf.BoolValue value) {
      if (attendedIndicatorBuilder_ == null) {
        if (attendedIndicator_ != null) {
          attendedIndicator_ =
            com.google.protobuf.BoolValue.newBuilder(attendedIndicator_).mergeFrom(value).buildPartial();
        } else {
          attendedIndicator_ = value;
        }
        onChanged();
      } else {
        attendedIndicatorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
     */
    public Builder clearAttendedIndicator() {
      if (attendedIndicatorBuilder_ == null) {
        attendedIndicator_ = null;
        onChanged();
      } else {
        attendedIndicator_ = null;
        attendedIndicatorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
     */
    public com.google.protobuf.BoolValue.Builder getAttendedIndicatorBuilder() {
      
      onChanged();
      return getAttendedIndicatorFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getAttendedIndicatorOrBuilder() {
      if (attendedIndicatorBuilder_ != null) {
        return attendedIndicatorBuilder_.getMessageOrBuilder();
      } else {
        return attendedIndicator_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : attendedIndicator_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue attendedIndicator = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getAttendedIndicatorFieldBuilder() {
      if (attendedIndicatorBuilder_ == null) {
        attendedIndicatorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getAttendedIndicator(),
                getParentForChildren(),
                isClean());
        attendedIndicator_ = null;
      }
      return attendedIndicatorBuilder_;
    }

    private java.util.List<com.bbva.business.gateway.iso20022.AdditionalData> additionalData_ =
      java.util.Collections.emptyList();
    private void ensureAdditionalDataIsMutable() {
      if (!((bitField0_ & 0x00000400) == 0x00000400)) {
        additionalData_ = new java.util.ArrayList<com.bbva.business.gateway.iso20022.AdditionalData>(additionalData_);
        bitField0_ |= 0x00000400;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bbva.business.gateway.iso20022.AdditionalData, com.bbva.business.gateway.iso20022.AdditionalData.Builder, com.bbva.business.gateway.iso20022.AdditionalDataOrBuilder> additionalDataBuilder_;

    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public java.util.List<com.bbva.business.gateway.iso20022.AdditionalData> getAdditionalDataList() {
      if (additionalDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(additionalData_);
      } else {
        return additionalDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public int getAdditionalDataCount() {
      if (additionalDataBuilder_ == null) {
        return additionalData_.size();
      } else {
        return additionalDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public com.bbva.business.gateway.iso20022.AdditionalData getAdditionalData(int index) {
      if (additionalDataBuilder_ == null) {
        return additionalData_.get(index);
      } else {
        return additionalDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public Builder setAdditionalData(
        int index, com.bbva.business.gateway.iso20022.AdditionalData value) {
      if (additionalDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdditionalDataIsMutable();
        additionalData_.set(index, value);
        onChanged();
      } else {
        additionalDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public Builder setAdditionalData(
        int index, com.bbva.business.gateway.iso20022.AdditionalData.Builder builderForValue) {
      if (additionalDataBuilder_ == null) {
        ensureAdditionalDataIsMutable();
        additionalData_.set(index, builderForValue.build());
        onChanged();
      } else {
        additionalDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public Builder addAdditionalData(com.bbva.business.gateway.iso20022.AdditionalData value) {
      if (additionalDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdditionalDataIsMutable();
        additionalData_.add(value);
        onChanged();
      } else {
        additionalDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public Builder addAdditionalData(
        int index, com.bbva.business.gateway.iso20022.AdditionalData value) {
      if (additionalDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdditionalDataIsMutable();
        additionalData_.add(index, value);
        onChanged();
      } else {
        additionalDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public Builder addAdditionalData(
        com.bbva.business.gateway.iso20022.AdditionalData.Builder builderForValue) {
      if (additionalDataBuilder_ == null) {
        ensureAdditionalDataIsMutable();
        additionalData_.add(builderForValue.build());
        onChanged();
      } else {
        additionalDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public Builder addAdditionalData(
        int index, com.bbva.business.gateway.iso20022.AdditionalData.Builder builderForValue) {
      if (additionalDataBuilder_ == null) {
        ensureAdditionalDataIsMutable();
        additionalData_.add(index, builderForValue.build());
        onChanged();
      } else {
        additionalDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public Builder addAllAdditionalData(
        java.lang.Iterable<? extends com.bbva.business.gateway.iso20022.AdditionalData> values) {
      if (additionalDataBuilder_ == null) {
        ensureAdditionalDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, additionalData_);
        onChanged();
      } else {
        additionalDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public Builder clearAdditionalData() {
      if (additionalDataBuilder_ == null) {
        additionalData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
      } else {
        additionalDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public Builder removeAdditionalData(int index) {
      if (additionalDataBuilder_ == null) {
        ensureAdditionalDataIsMutable();
        additionalData_.remove(index);
        onChanged();
      } else {
        additionalDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public com.bbva.business.gateway.iso20022.AdditionalData.Builder getAdditionalDataBuilder(
        int index) {
      return getAdditionalDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public com.bbva.business.gateway.iso20022.AdditionalDataOrBuilder getAdditionalDataOrBuilder(
        int index) {
      if (additionalDataBuilder_ == null) {
        return additionalData_.get(index);  } else {
        return additionalDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public java.util.List<? extends com.bbva.business.gateway.iso20022.AdditionalDataOrBuilder> 
         getAdditionalDataOrBuilderList() {
      if (additionalDataBuilder_ != null) {
        return additionalDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(additionalData_);
      }
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public com.bbva.business.gateway.iso20022.AdditionalData.Builder addAdditionalDataBuilder() {
      return getAdditionalDataFieldBuilder().addBuilder(
          com.bbva.business.gateway.iso20022.AdditionalData.getDefaultInstance());
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public com.bbva.business.gateway.iso20022.AdditionalData.Builder addAdditionalDataBuilder(
        int index) {
      return getAdditionalDataFieldBuilder().addBuilder(
          index, com.bbva.business.gateway.iso20022.AdditionalData.getDefaultInstance());
    }
    /**
     * <code>repeated .b.gateway.v1.AdditionalData additionalData = 11;</code>
     */
    public java.util.List<com.bbva.business.gateway.iso20022.AdditionalData.Builder> 
         getAdditionalDataBuilderList() {
      return getAdditionalDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bbva.business.gateway.iso20022.AdditionalData, com.bbva.business.gateway.iso20022.AdditionalData.Builder, com.bbva.business.gateway.iso20022.AdditionalDataOrBuilder> 
        getAdditionalDataFieldBuilder() {
      if (additionalDataBuilder_ == null) {
        additionalDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.bbva.business.gateway.iso20022.AdditionalData, com.bbva.business.gateway.iso20022.AdditionalData.Builder, com.bbva.business.gateway.iso20022.AdditionalDataOrBuilder>(
                additionalData_,
                ((bitField0_ & 0x00000400) == 0x00000400),
                getParentForChildren(),
                isClean());
        additionalData_ = null;
      }
      return additionalDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:b.gateway.v1.PointOfServiceContext)
  }

  // @@protoc_insertion_point(class_scope:b.gateway.v1.PointOfServiceContext)
  private static final com.bbva.business.gateway.iso20022.PointOfServiceContext DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bbva.business.gateway.iso20022.PointOfServiceContext();
  }

  public static com.bbva.business.gateway.iso20022.PointOfServiceContext getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PointOfServiceContext>
      PARSER = new com.google.protobuf.AbstractParser<PointOfServiceContext>() {
    @java.lang.Override
    public PointOfServiceContext parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PointOfServiceContext(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PointOfServiceContext> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PointOfServiceContext> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bbva.business.gateway.iso20022.PointOfServiceContext getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

