// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

public interface ReceiverOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.Receiver)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>.google.protobuf.StringValue id = 1;</code>
   */
  com.google.protobuf.StringValue getId();
  /**
   * <code>.google.protobuf.StringValue id = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getIdOrBuilder();
}
