// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

/**
 * Protobuf type {@code b.gateway.v1.SpecialProgrammeQualification}
 */
public  final class SpecialProgrammeQualification extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:b.gateway.v1.SpecialProgrammeQualification)
    SpecialProgrammeQualificationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SpecialProgrammeQualification.newBuilder() to construct.
  private SpecialProgrammeQualification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SpecialProgrammeQualification() {
    detail_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SpecialProgrammeQualification(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              detail_ = new java.util.ArrayList<com.bbva.business.gateway.iso20022.Detail>();
              mutable_bitField0_ |= 0x00000001;
            }
            detail_.add(
                input.readMessage(com.bbva.business.gateway.iso20022.Detail.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        detail_ = java.util.Collections.unmodifiableList(detail_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_SpecialProgrammeQualification_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_SpecialProgrammeQualification_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bbva.business.gateway.iso20022.SpecialProgrammeQualification.class, com.bbva.business.gateway.iso20022.SpecialProgrammeQualification.Builder.class);
  }

  public static final int DETAIL_FIELD_NUMBER = 1;
  private java.util.List<com.bbva.business.gateway.iso20022.Detail> detail_;
  /**
   * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
   */
  public java.util.List<com.bbva.business.gateway.iso20022.Detail> getDetailList() {
    return detail_;
  }
  /**
   * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
   */
  public java.util.List<? extends com.bbva.business.gateway.iso20022.DetailOrBuilder> 
      getDetailOrBuilderList() {
    return detail_;
  }
  /**
   * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
   */
  public int getDetailCount() {
    return detail_.size();
  }
  /**
   * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
   */
  public com.bbva.business.gateway.iso20022.Detail getDetail(int index) {
    return detail_.get(index);
  }
  /**
   * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
   */
  public com.bbva.business.gateway.iso20022.DetailOrBuilder getDetailOrBuilder(
      int index) {
    return detail_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < detail_.size(); i++) {
      output.writeMessage(1, detail_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < detail_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, detail_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bbva.business.gateway.iso20022.SpecialProgrammeQualification)) {
      return super.equals(obj);
    }
    com.bbva.business.gateway.iso20022.SpecialProgrammeQualification other = (com.bbva.business.gateway.iso20022.SpecialProgrammeQualification) obj;

    boolean result = true;
    result = result && getDetailList()
        .equals(other.getDetailList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDetailCount() > 0) {
      hash = (37 * hash) + DETAIL_FIELD_NUMBER;
      hash = (53 * hash) + getDetailList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bbva.business.gateway.iso20022.SpecialProgrammeQualification parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.SpecialProgrammeQualification parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.SpecialProgrammeQualification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.SpecialProgrammeQualification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.SpecialProgrammeQualification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.SpecialProgrammeQualification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.SpecialProgrammeQualification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.SpecialProgrammeQualification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.SpecialProgrammeQualification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.SpecialProgrammeQualification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.SpecialProgrammeQualification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.SpecialProgrammeQualification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bbva.business.gateway.iso20022.SpecialProgrammeQualification prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code b.gateway.v1.SpecialProgrammeQualification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:b.gateway.v1.SpecialProgrammeQualification)
      com.bbva.business.gateway.iso20022.SpecialProgrammeQualificationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_SpecialProgrammeQualification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_SpecialProgrammeQualification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbva.business.gateway.iso20022.SpecialProgrammeQualification.class, com.bbva.business.gateway.iso20022.SpecialProgrammeQualification.Builder.class);
    }

    // Construct using com.bbva.business.gateway.iso20022.SpecialProgrammeQualification.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDetailFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (detailBuilder_ == null) {
        detail_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        detailBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_SpecialProgrammeQualification_descriptor;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.SpecialProgrammeQualification getDefaultInstanceForType() {
      return com.bbva.business.gateway.iso20022.SpecialProgrammeQualification.getDefaultInstance();
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.SpecialProgrammeQualification build() {
      com.bbva.business.gateway.iso20022.SpecialProgrammeQualification result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.SpecialProgrammeQualification buildPartial() {
      com.bbva.business.gateway.iso20022.SpecialProgrammeQualification result = new com.bbva.business.gateway.iso20022.SpecialProgrammeQualification(this);
      int from_bitField0_ = bitField0_;
      if (detailBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          detail_ = java.util.Collections.unmodifiableList(detail_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.detail_ = detail_;
      } else {
        result.detail_ = detailBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bbva.business.gateway.iso20022.SpecialProgrammeQualification) {
        return mergeFrom((com.bbva.business.gateway.iso20022.SpecialProgrammeQualification)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bbva.business.gateway.iso20022.SpecialProgrammeQualification other) {
      if (other == com.bbva.business.gateway.iso20022.SpecialProgrammeQualification.getDefaultInstance()) return this;
      if (detailBuilder_ == null) {
        if (!other.detail_.isEmpty()) {
          if (detail_.isEmpty()) {
            detail_ = other.detail_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDetailIsMutable();
            detail_.addAll(other.detail_);
          }
          onChanged();
        }
      } else {
        if (!other.detail_.isEmpty()) {
          if (detailBuilder_.isEmpty()) {
            detailBuilder_.dispose();
            detailBuilder_ = null;
            detail_ = other.detail_;
            bitField0_ = (bitField0_ & ~0x00000001);
            detailBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDetailFieldBuilder() : null;
          } else {
            detailBuilder_.addAllMessages(other.detail_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bbva.business.gateway.iso20022.SpecialProgrammeQualification parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bbva.business.gateway.iso20022.SpecialProgrammeQualification) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.bbva.business.gateway.iso20022.Detail> detail_ =
      java.util.Collections.emptyList();
    private void ensureDetailIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        detail_ = new java.util.ArrayList<com.bbva.business.gateway.iso20022.Detail>(detail_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bbva.business.gateway.iso20022.Detail, com.bbva.business.gateway.iso20022.Detail.Builder, com.bbva.business.gateway.iso20022.DetailOrBuilder> detailBuilder_;

    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public java.util.List<com.bbva.business.gateway.iso20022.Detail> getDetailList() {
      if (detailBuilder_ == null) {
        return java.util.Collections.unmodifiableList(detail_);
      } else {
        return detailBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public int getDetailCount() {
      if (detailBuilder_ == null) {
        return detail_.size();
      } else {
        return detailBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public com.bbva.business.gateway.iso20022.Detail getDetail(int index) {
      if (detailBuilder_ == null) {
        return detail_.get(index);
      } else {
        return detailBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public Builder setDetail(
        int index, com.bbva.business.gateway.iso20022.Detail value) {
      if (detailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDetailIsMutable();
        detail_.set(index, value);
        onChanged();
      } else {
        detailBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public Builder setDetail(
        int index, com.bbva.business.gateway.iso20022.Detail.Builder builderForValue) {
      if (detailBuilder_ == null) {
        ensureDetailIsMutable();
        detail_.set(index, builderForValue.build());
        onChanged();
      } else {
        detailBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public Builder addDetail(com.bbva.business.gateway.iso20022.Detail value) {
      if (detailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDetailIsMutable();
        detail_.add(value);
        onChanged();
      } else {
        detailBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public Builder addDetail(
        int index, com.bbva.business.gateway.iso20022.Detail value) {
      if (detailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDetailIsMutable();
        detail_.add(index, value);
        onChanged();
      } else {
        detailBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public Builder addDetail(
        com.bbva.business.gateway.iso20022.Detail.Builder builderForValue) {
      if (detailBuilder_ == null) {
        ensureDetailIsMutable();
        detail_.add(builderForValue.build());
        onChanged();
      } else {
        detailBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public Builder addDetail(
        int index, com.bbva.business.gateway.iso20022.Detail.Builder builderForValue) {
      if (detailBuilder_ == null) {
        ensureDetailIsMutable();
        detail_.add(index, builderForValue.build());
        onChanged();
      } else {
        detailBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public Builder addAllDetail(
        java.lang.Iterable<? extends com.bbva.business.gateway.iso20022.Detail> values) {
      if (detailBuilder_ == null) {
        ensureDetailIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, detail_);
        onChanged();
      } else {
        detailBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public Builder clearDetail() {
      if (detailBuilder_ == null) {
        detail_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        detailBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public Builder removeDetail(int index) {
      if (detailBuilder_ == null) {
        ensureDetailIsMutable();
        detail_.remove(index);
        onChanged();
      } else {
        detailBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public com.bbva.business.gateway.iso20022.Detail.Builder getDetailBuilder(
        int index) {
      return getDetailFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public com.bbva.business.gateway.iso20022.DetailOrBuilder getDetailOrBuilder(
        int index) {
      if (detailBuilder_ == null) {
        return detail_.get(index);  } else {
        return detailBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public java.util.List<? extends com.bbva.business.gateway.iso20022.DetailOrBuilder> 
         getDetailOrBuilderList() {
      if (detailBuilder_ != null) {
        return detailBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(detail_);
      }
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public com.bbva.business.gateway.iso20022.Detail.Builder addDetailBuilder() {
      return getDetailFieldBuilder().addBuilder(
          com.bbva.business.gateway.iso20022.Detail.getDefaultInstance());
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public com.bbva.business.gateway.iso20022.Detail.Builder addDetailBuilder(
        int index) {
      return getDetailFieldBuilder().addBuilder(
          index, com.bbva.business.gateway.iso20022.Detail.getDefaultInstance());
    }
    /**
     * <code>repeated .b.gateway.v1.Detail detail = 1;</code>
     */
    public java.util.List<com.bbva.business.gateway.iso20022.Detail.Builder> 
         getDetailBuilderList() {
      return getDetailFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bbva.business.gateway.iso20022.Detail, com.bbva.business.gateway.iso20022.Detail.Builder, com.bbva.business.gateway.iso20022.DetailOrBuilder> 
        getDetailFieldBuilder() {
      if (detailBuilder_ == null) {
        detailBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.bbva.business.gateway.iso20022.Detail, com.bbva.business.gateway.iso20022.Detail.Builder, com.bbva.business.gateway.iso20022.DetailOrBuilder>(
                detail_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        detail_ = null;
      }
      return detailBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:b.gateway.v1.SpecialProgrammeQualification)
  }

  // @@protoc_insertion_point(class_scope:b.gateway.v1.SpecialProgrammeQualification)
  private static final com.bbva.business.gateway.iso20022.SpecialProgrammeQualification DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bbva.business.gateway.iso20022.SpecialProgrammeQualification();
  }

  public static com.bbva.business.gateway.iso20022.SpecialProgrammeQualification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpecialProgrammeQualification>
      PARSER = new com.google.protobuf.AbstractParser<SpecialProgrammeQualification>() {
    @java.lang.Override
    public SpecialProgrammeQualification parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SpecialProgrammeQualification(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SpecialProgrammeQualification> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SpecialProgrammeQualification> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bbva.business.gateway.iso20022.SpecialProgrammeQualification getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

