// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

public interface SummarySaleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.SummarySale)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.b.gateway.v1.LoyaltyProgramme loyaltyProgramme = 1;</code>
   */
  boolean hasLoyaltyProgramme();
  /**
   * <code>.b.gateway.v1.LoyaltyProgramme loyaltyProgramme = 1;</code>
   */
  com.bbva.business.gateway.iso20022.LoyaltyProgramme getLoyaltyProgramme();
  /**
   * <code>.b.gateway.v1.LoyaltyProgramme loyaltyProgramme = 1;</code>
   */
  com.bbva.business.gateway.iso20022.LoyaltyProgrammeOrBuilder getLoyaltyProgrammeOrBuilder();

  /**
   * <code>repeated .b.gateway.v1.Adjustment adjustment = 2;</code>
   */
  java.util.List<com.bbva.business.gateway.iso20022.Adjustment> 
      getAdjustmentList();
  /**
   * <code>repeated .b.gateway.v1.Adjustment adjustment = 2;</code>
   */
  com.bbva.business.gateway.iso20022.Adjustment getAdjustment(int index);
  /**
   * <code>repeated .b.gateway.v1.Adjustment adjustment = 2;</code>
   */
  int getAdjustmentCount();
  /**
   * <code>repeated .b.gateway.v1.Adjustment adjustment = 2;</code>
   */
  java.util.List<? extends com.bbva.business.gateway.iso20022.AdjustmentOrBuilder> 
      getAdjustmentOrBuilderList();
  /**
   * <code>repeated .b.gateway.v1.Adjustment adjustment = 2;</code>
   */
  com.bbva.business.gateway.iso20022.AdjustmentOrBuilder getAdjustmentOrBuilder(
      int index);
}
