// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

public interface TerminalIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.TerminalId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>.google.protobuf.StringValue id = 1;</code>
   */
  com.google.protobuf.StringValue getId();
  /**
   * <code>.google.protobuf.StringValue id = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getIdOrBuilder();

  /**
   * <code>.google.protobuf.StringValue assigner = 2;</code>
   */
  boolean hasAssigner();
  /**
   * <code>.google.protobuf.StringValue assigner = 2;</code>
   */
  com.google.protobuf.StringValue getAssigner();
  /**
   * <code>.google.protobuf.StringValue assigner = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getAssignerOrBuilder();

  /**
   * <code>.google.protobuf.StringValue country = 3;</code>
   */
  boolean hasCountry();
  /**
   * <code>.google.protobuf.StringValue country = 3;</code>
   */
  com.google.protobuf.StringValue getCountry();
  /**
   * <code>.google.protobuf.StringValue country = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getCountryOrBuilder();
}
