// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

/**
 * Protobuf type {@code b.gateway.v1.Track2}
 */
public  final class Track2 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:b.gateway.v1.Track2)
    Track2OrBuilder {
private static final long serialVersionUID = 0L;
  // Use Track2.newBuilder() to construct.
  private Track2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Track2() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Track2(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (textValue_ != null) {
              subBuilder = textValue_.toBuilder();
            }
            textValue_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(textValue_);
              textValue_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_Track2_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_Track2_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bbva.business.gateway.iso20022.Track2.class, com.bbva.business.gateway.iso20022.Track2.Builder.class);
  }

  public static final int TEXTVALUE_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue textValue_;
  /**
   * <code>.google.protobuf.StringValue textValue = 1;</code>
   */
  public boolean hasTextValue() {
    return textValue_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue textValue = 1;</code>
   */
  public com.google.protobuf.StringValue getTextValue() {
    return textValue_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : textValue_;
  }
  /**
   * <code>.google.protobuf.StringValue textValue = 1;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getTextValueOrBuilder() {
    return getTextValue();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (textValue_ != null) {
      output.writeMessage(1, getTextValue());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (textValue_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTextValue());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bbva.business.gateway.iso20022.Track2)) {
      return super.equals(obj);
    }
    com.bbva.business.gateway.iso20022.Track2 other = (com.bbva.business.gateway.iso20022.Track2) obj;

    boolean result = true;
    result = result && (hasTextValue() == other.hasTextValue());
    if (hasTextValue()) {
      result = result && getTextValue()
          .equals(other.getTextValue());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTextValue()) {
      hash = (37 * hash) + TEXTVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getTextValue().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bbva.business.gateway.iso20022.Track2 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.Track2 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.Track2 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.Track2 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.Track2 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.business.gateway.iso20022.Track2 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.Track2 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.Track2 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.Track2 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.Track2 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bbva.business.gateway.iso20022.Track2 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bbva.business.gateway.iso20022.Track2 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bbva.business.gateway.iso20022.Track2 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code b.gateway.v1.Track2}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:b.gateway.v1.Track2)
      com.bbva.business.gateway.iso20022.Track2OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_Track2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_Track2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbva.business.gateway.iso20022.Track2.class, com.bbva.business.gateway.iso20022.Track2.Builder.class);
    }

    // Construct using com.bbva.business.gateway.iso20022.Track2.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (textValueBuilder_ == null) {
        textValue_ = null;
      } else {
        textValue_ = null;
        textValueBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bbva.business.gateway.iso20022.Iso20022.internal_static_b_gateway_v1_Track2_descriptor;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.Track2 getDefaultInstanceForType() {
      return com.bbva.business.gateway.iso20022.Track2.getDefaultInstance();
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.Track2 build() {
      com.bbva.business.gateway.iso20022.Track2 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bbva.business.gateway.iso20022.Track2 buildPartial() {
      com.bbva.business.gateway.iso20022.Track2 result = new com.bbva.business.gateway.iso20022.Track2(this);
      if (textValueBuilder_ == null) {
        result.textValue_ = textValue_;
      } else {
        result.textValue_ = textValueBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bbva.business.gateway.iso20022.Track2) {
        return mergeFrom((com.bbva.business.gateway.iso20022.Track2)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bbva.business.gateway.iso20022.Track2 other) {
      if (other == com.bbva.business.gateway.iso20022.Track2.getDefaultInstance()) return this;
      if (other.hasTextValue()) {
        mergeTextValue(other.getTextValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bbva.business.gateway.iso20022.Track2 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bbva.business.gateway.iso20022.Track2) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.StringValue textValue_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> textValueBuilder_;
    /**
     * <code>.google.protobuf.StringValue textValue = 1;</code>
     */
    public boolean hasTextValue() {
      return textValueBuilder_ != null || textValue_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue textValue = 1;</code>
     */
    public com.google.protobuf.StringValue getTextValue() {
      if (textValueBuilder_ == null) {
        return textValue_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : textValue_;
      } else {
        return textValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue textValue = 1;</code>
     */
    public Builder setTextValue(com.google.protobuf.StringValue value) {
      if (textValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        textValue_ = value;
        onChanged();
      } else {
        textValueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue textValue = 1;</code>
     */
    public Builder setTextValue(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (textValueBuilder_ == null) {
        textValue_ = builderForValue.build();
        onChanged();
      } else {
        textValueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue textValue = 1;</code>
     */
    public Builder mergeTextValue(com.google.protobuf.StringValue value) {
      if (textValueBuilder_ == null) {
        if (textValue_ != null) {
          textValue_ =
            com.google.protobuf.StringValue.newBuilder(textValue_).mergeFrom(value).buildPartial();
        } else {
          textValue_ = value;
        }
        onChanged();
      } else {
        textValueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue textValue = 1;</code>
     */
    public Builder clearTextValue() {
      if (textValueBuilder_ == null) {
        textValue_ = null;
        onChanged();
      } else {
        textValue_ = null;
        textValueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue textValue = 1;</code>
     */
    public com.google.protobuf.StringValue.Builder getTextValueBuilder() {
      
      onChanged();
      return getTextValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue textValue = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getTextValueOrBuilder() {
      if (textValueBuilder_ != null) {
        return textValueBuilder_.getMessageOrBuilder();
      } else {
        return textValue_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : textValue_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue textValue = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getTextValueFieldBuilder() {
      if (textValueBuilder_ == null) {
        textValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getTextValue(),
                getParentForChildren(),
                isClean());
        textValue_ = null;
      }
      return textValueBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:b.gateway.v1.Track2)
  }

  // @@protoc_insertion_point(class_scope:b.gateway.v1.Track2)
  private static final com.bbva.business.gateway.iso20022.Track2 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bbva.business.gateway.iso20022.Track2();
  }

  public static com.bbva.business.gateway.iso20022.Track2 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Track2>
      PARSER = new com.google.protobuf.AbstractParser<Track2>() {
    @java.lang.Override
    public Track2 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Track2(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Track2> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Track2> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bbva.business.gateway.iso20022.Track2 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

