// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

public interface TransactionContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.TransactionContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.b.gateway.v1.SettlementService settlementService = 1;</code>
   */
  boolean hasSettlementService();
  /**
   * <code>.b.gateway.v1.SettlementService settlementService = 1;</code>
   */
  com.bbva.business.gateway.iso20022.SettlementService getSettlementService();
  /**
   * <code>.b.gateway.v1.SettlementService settlementService = 1;</code>
   */
  com.bbva.business.gateway.iso20022.SettlementServiceOrBuilder getSettlementServiceOrBuilder();

  /**
   * <code>.google.protobuf.StringValue captureDate = 2;</code>
   */
  boolean hasCaptureDate();
  /**
   * <code>.google.protobuf.StringValue captureDate = 2;</code>
   */
  com.google.protobuf.StringValue getCaptureDate();
  /**
   * <code>.google.protobuf.StringValue captureDate = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getCaptureDateOrBuilder();

  /**
   * <code>.google.protobuf.StringValue merchantCategoryCode = 3;</code>
   */
  boolean hasMerchantCategoryCode();
  /**
   * <code>.google.protobuf.StringValue merchantCategoryCode = 3;</code>
   */
  com.google.protobuf.StringValue getMerchantCategoryCode();
  /**
   * <code>.google.protobuf.StringValue merchantCategoryCode = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getMerchantCategoryCodeOrBuilder();

  /**
   * <code>.google.protobuf.StringValue merchantCategorySpecificData = 4;</code>
   */
  boolean hasMerchantCategorySpecificData();
  /**
   * <code>.google.protobuf.StringValue merchantCategorySpecificData = 4;</code>
   */
  com.google.protobuf.StringValue getMerchantCategorySpecificData();
  /**
   * <code>.google.protobuf.StringValue merchantCategorySpecificData = 4;</code>
   */
  com.google.protobuf.StringValueOrBuilder getMerchantCategorySpecificDataOrBuilder();

  /**
   * <code>.b.gateway.v1.Reconciliation reconciliation = 5;</code>
   */
  boolean hasReconciliation();
  /**
   * <code>.b.gateway.v1.Reconciliation reconciliation = 5;</code>
   */
  com.bbva.business.gateway.iso20022.Reconciliation getReconciliation();
  /**
   * <code>.b.gateway.v1.Reconciliation reconciliation = 5;</code>
   */
  com.bbva.business.gateway.iso20022.ReconciliationOrBuilder getReconciliationOrBuilder();

  /**
   * <code>.google.protobuf.StringValue transactionInitiator = 6;</code>
   */
  boolean hasTransactionInitiator();
  /**
   * <code>.google.protobuf.StringValue transactionInitiator = 6;</code>
   */
  com.google.protobuf.StringValue getTransactionInitiator();
  /**
   * <code>.google.protobuf.StringValue transactionInitiator = 6;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTransactionInitiatorOrBuilder();

  /**
   * <code>.google.protobuf.StringValue iCCFallbackIndicator = 7;</code>
   */
  boolean hasICCFallbackIndicator();
  /**
   * <code>.google.protobuf.StringValue iCCFallbackIndicator = 7;</code>
   */
  com.google.protobuf.StringValue getICCFallbackIndicator();
  /**
   * <code>.google.protobuf.StringValue iCCFallbackIndicator = 7;</code>
   */
  com.google.protobuf.StringValueOrBuilder getICCFallbackIndicatorOrBuilder();

  /**
   * <code>.google.protobuf.StringValue magneticStripeFallbackIndicator = 8;</code>
   */
  boolean hasMagneticStripeFallbackIndicator();
  /**
   * <code>.google.protobuf.StringValue magneticStripeFallbackIndicator = 8;</code>
   */
  com.google.protobuf.StringValue getMagneticStripeFallbackIndicator();
  /**
   * <code>.google.protobuf.StringValue magneticStripeFallbackIndicator = 8;</code>
   */
  com.google.protobuf.StringValueOrBuilder getMagneticStripeFallbackIndicatorOrBuilder();

  /**
   * <code>.google.protobuf.BoolValue reSubmissionIndicator = 9;</code>
   */
  boolean hasReSubmissionIndicator();
  /**
   * <code>.google.protobuf.BoolValue reSubmissionIndicator = 9;</code>
   */
  com.google.protobuf.BoolValue getReSubmissionIndicator();
  /**
   * <code>.google.protobuf.BoolValue reSubmissionIndicator = 9;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getReSubmissionIndicatorOrBuilder();

  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 10;</code>
   */
  java.util.List<com.bbva.business.gateway.iso20022.AdditionalData> 
      getAdditionalDataList();
  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 10;</code>
   */
  com.bbva.business.gateway.iso20022.AdditionalData getAdditionalData(int index);
  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 10;</code>
   */
  int getAdditionalDataCount();
  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 10;</code>
   */
  java.util.List<? extends com.bbva.business.gateway.iso20022.AdditionalDataOrBuilder> 
      getAdditionalDataOrBuilderList();
  /**
   * <code>repeated .b.gateway.v1.AdditionalData additionalData = 10;</code>
   */
  com.bbva.business.gateway.iso20022.AdditionalDataOrBuilder getAdditionalDataOrBuilder(
      int index);
}
