// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

public interface TransactionIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.TransactionId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue transactionReference = 1;</code>
   */
  boolean hasTransactionReference();
  /**
   * <code>.google.protobuf.StringValue transactionReference = 1;</code>
   */
  com.google.protobuf.StringValue getTransactionReference();
  /**
   * <code>.google.protobuf.StringValue transactionReference = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTransactionReferenceOrBuilder();

  /**
   * <code>.google.protobuf.StringValue transmissionDateTime = 2;</code>
   */
  boolean hasTransmissionDateTime();
  /**
   * <code>.google.protobuf.StringValue transmissionDateTime = 2;</code>
   */
  com.google.protobuf.StringValue getTransmissionDateTime();
  /**
   * <code>.google.protobuf.StringValue transmissionDateTime = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTransmissionDateTimeOrBuilder();

  /**
   * <code>.google.protobuf.StringValue systemTraceAuditNumber = 3;</code>
   */
  boolean hasSystemTraceAuditNumber();
  /**
   * <code>.google.protobuf.StringValue systemTraceAuditNumber = 3;</code>
   */
  com.google.protobuf.StringValue getSystemTraceAuditNumber();
  /**
   * <code>.google.protobuf.StringValue systemTraceAuditNumber = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getSystemTraceAuditNumberOrBuilder();

  /**
   * <code>.google.protobuf.StringValue localDate = 4;</code>
   */
  boolean hasLocalDate();
  /**
   * <code>.google.protobuf.StringValue localDate = 4;</code>
   */
  com.google.protobuf.StringValue getLocalDate();
  /**
   * <code>.google.protobuf.StringValue localDate = 4;</code>
   */
  com.google.protobuf.StringValueOrBuilder getLocalDateOrBuilder();

  /**
   * <code>.google.protobuf.StringValue localTime = 5;</code>
   */
  boolean hasLocalTime();
  /**
   * <code>.google.protobuf.StringValue localTime = 5;</code>
   */
  com.google.protobuf.StringValue getLocalTime();
  /**
   * <code>.google.protobuf.StringValue localTime = 5;</code>
   */
  com.google.protobuf.StringValueOrBuilder getLocalTimeOrBuilder();

  /**
   * <code>.google.protobuf.StringValue localDateTime = 6;</code>
   */
  boolean hasLocalDateTime();
  /**
   * <code>.google.protobuf.StringValue localDateTime = 6;</code>
   */
  com.google.protobuf.StringValue getLocalDateTime();
  /**
   * <code>.google.protobuf.StringValue localDateTime = 6;</code>
   */
  com.google.protobuf.StringValueOrBuilder getLocalDateTimeOrBuilder();

  /**
   * <code>.google.protobuf.StringValue acquirerReferenceData = 7;</code>
   */
  boolean hasAcquirerReferenceData();
  /**
   * <code>.google.protobuf.StringValue acquirerReferenceData = 7;</code>
   */
  com.google.protobuf.StringValue getAcquirerReferenceData();
  /**
   * <code>.google.protobuf.StringValue acquirerReferenceData = 7;</code>
   */
  com.google.protobuf.StringValueOrBuilder getAcquirerReferenceDataOrBuilder();

  /**
   * <code>.google.protobuf.StringValue retrievalReferenceNumber = 8;</code>
   */
  boolean hasRetrievalReferenceNumber();
  /**
   * <code>.google.protobuf.StringValue retrievalReferenceNumber = 8;</code>
   */
  com.google.protobuf.StringValue getRetrievalReferenceNumber();
  /**
   * <code>.google.protobuf.StringValue retrievalReferenceNumber = 8;</code>
   */
  com.google.protobuf.StringValueOrBuilder getRetrievalReferenceNumberOrBuilder();

  /**
   * <code>.b.gateway.v1.OriginalDataElements originalDataElements = 9;</code>
   */
  boolean hasOriginalDataElements();
  /**
   * <code>.b.gateway.v1.OriginalDataElements originalDataElements = 9;</code>
   */
  com.bbva.business.gateway.iso20022.OriginalDataElements getOriginalDataElements();
  /**
   * <code>.b.gateway.v1.OriginalDataElements originalDataElements = 9;</code>
   */
  com.bbva.business.gateway.iso20022.OriginalDataElementsOrBuilder getOriginalDataElementsOrBuilder();

  /**
   * <code>.google.protobuf.StringValue cardIssuerReferenceData = 10;</code>
   */
  boolean hasCardIssuerReferenceData();
  /**
   * <code>.google.protobuf.StringValue cardIssuerReferenceData = 10;</code>
   */
  com.google.protobuf.StringValue getCardIssuerReferenceData();
  /**
   * <code>.google.protobuf.StringValue cardIssuerReferenceData = 10;</code>
   */
  com.google.protobuf.StringValueOrBuilder getCardIssuerReferenceDataOrBuilder();
}
