// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

public interface VerificationInformationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.VerificationInformation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue key = 1;</code>
   */
  boolean hasKey();
  /**
   * <code>.google.protobuf.StringValue key = 1;</code>
   */
  com.google.protobuf.StringValue getKey();
  /**
   * <code>.google.protobuf.StringValue key = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getKeyOrBuilder();

  /**
   * <code>.b.gateway.v1.Value value = 2;</code>
   */
  boolean hasValue();
  /**
   * <code>.b.gateway.v1.Value value = 2;</code>
   */
  com.bbva.business.gateway.iso20022.Value getValue();
  /**
   * <code>.b.gateway.v1.Value value = 2;</code>
   */
  com.bbva.business.gateway.iso20022.ValueOrBuilder getValueOrBuilder();
}
