// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iso20022.proto

package com.bbva.business.gateway.iso20022;

public interface VerificationResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.VerificationResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue key = 1;</code>
   */
  boolean hasKey();
  /**
   * <code>.google.protobuf.StringValue key = 1;</code>
   */
  com.google.protobuf.StringValue getKey();
  /**
   * <code>.google.protobuf.StringValue key = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getKeyOrBuilder();

  /**
   * <code>.google.protobuf.StringValue entity = 2;</code>
   */
  boolean hasEntity();
  /**
   * <code>.google.protobuf.StringValue entity = 2;</code>
   */
  com.google.protobuf.StringValue getEntity();
  /**
   * <code>.google.protobuf.StringValue entity = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getEntityOrBuilder();

  /**
   * <code>.google.protobuf.StringValue otherEntity = 3;</code>
   */
  boolean hasOtherEntity();
  /**
   * <code>.google.protobuf.StringValue otherEntity = 3;</code>
   */
  com.google.protobuf.StringValue getOtherEntity();
  /**
   * <code>.google.protobuf.StringValue otherEntity = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getOtherEntityOrBuilder();

  /**
   * <code>.google.protobuf.StringValue otherResult = 4;</code>
   */
  boolean hasOtherResult();
  /**
   * <code>.google.protobuf.StringValue otherResult = 4;</code>
   */
  com.google.protobuf.StringValue getOtherResult();
  /**
   * <code>.google.protobuf.StringValue otherResult = 4;</code>
   */
  com.google.protobuf.StringValueOrBuilder getOtherResultOrBuilder();

  /**
   * <code>repeated .b.gateway.v1.ResultDetails resultDetails = 5;</code>
   */
  java.util.List<com.bbva.business.gateway.iso20022.ResultDetails> 
      getResultDetailsList();
  /**
   * <code>repeated .b.gateway.v1.ResultDetails resultDetails = 5;</code>
   */
  com.bbva.business.gateway.iso20022.ResultDetails getResultDetails(int index);
  /**
   * <code>repeated .b.gateway.v1.ResultDetails resultDetails = 5;</code>
   */
  int getResultDetailsCount();
  /**
   * <code>repeated .b.gateway.v1.ResultDetails resultDetails = 5;</code>
   */
  java.util.List<? extends com.bbva.business.gateway.iso20022.ResultDetailsOrBuilder> 
      getResultDetailsOrBuilderList();
  /**
   * <code>repeated .b.gateway.v1.ResultDetails resultDetails = 5;</code>
   */
  com.bbva.business.gateway.iso20022.ResultDetailsOrBuilder getResultDetailsOrBuilder(
      int index);
}
