spring:
  config:
    import:
      - classpath:application-data.yml
      - classpath:application-datalocal.yml
  profiles:
    group:
      gw: data, datalocal, sensitivedata

lombok:
  addLombokGeneratedAnnotation: true

logging:
  pattern:
    console: "%m%n"

server:
  port: 8083

