// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dummy.proto

package com.bbva.business.gateway.dummy;

public interface Iso20022DummyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:b.gateway.v1.Iso20022DummyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageFunction = 1;</code>
   */
  java.lang.String getMessageFunction();
  /**
   * <code>string messageFunction = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageFunctionBytes();

  /**
   * <code>string header = 2;</code>
   */
  java.lang.String getHeader();
  /**
   * <code>string header = 2;</code>
   */
  com.google.protobuf.ByteString
      getHeaderBytes();

  /**
   * <code>string systemTraceAuditNumber = 3;</code>
   */
  java.lang.String getSystemTraceAuditNumber();
  /**
   * <code>string systemTraceAuditNumber = 3;</code>
   */
  com.google.protobuf.ByteString
      getSystemTraceAuditNumberBytes();

  /**
   * <code>string retrievalReferenceNumber = 4;</code>
   */
  java.lang.String getRetrievalReferenceNumber();
  /**
   * <code>string retrievalReferenceNumber = 4;</code>
   */
  com.google.protobuf.ByteString
      getRetrievalReferenceNumberBytes();
}
