package com.bbva.gui.dto;

import com.bbva.orchestrator.parser.iso8583.ISO8583;

public class Metadata {

    public static MappingMetadata createMetadata(ISO8583 inputObject) {

        MappingMetadata mappingMetadata = new MappingMetadata();
        mappingMetadata.addFieldOrigin("[P063][" + inputObject.getNetworkData()+"]","traceData[posAdditionalData]");
        mappingMetadata.addFieldOrigin("[P002][" + inputObject.getPrimaryAccountNumber()+"]","Environment/Card/pan");
        mappingMetadata.addFieldOrigin("[P014]["+ inputObject.getDateExpiration()+"]","Environment/Card/expiryDate");
        mappingMetadata.addFieldOrigin("[P035][" + inputObject.getTrackTwoData()+"]","Environment/Card/track2");
        mappingMetadata.addFieldOrigin("[P045][" + inputObject.getTrackOneData()+"]","Environment/Card/track1");
        mappingMetadata.addFieldOrigin("[P041][" + inputObject.getCardAcceptorTerminalIdentification()+"]","Environment/Terminal/TerminalId/id");
        mappingMetadata.addFieldOrigin("[P060][" + inputObject.getPosTerminalData()+"]","Environment/Terminal/TerminalId/assigner");
        mappingMetadata.addFieldOrigin("[P032][" + inputObject.getAcquiringInstitutionIdentificationCode()+"]","Environment/Acquirer/id");
        mappingMetadata.addFieldOrigin("[P019][" + inputObject.getAcquirerCountryCode()+"]","Environment/Acquirer/country");
        mappingMetadata.addFieldOrigin("[P048]["+ inputObject.getAdditionalDataRetailer()+"]","Environment/Sender/additionalId[additionalDataRetailer]");
        mappingMetadata.addFieldOrigin("[P033][" + inputObject.getForwardingInstitutionIdentificationCode()+"]","Environment/Sender/id");
        mappingMetadata.addFieldOrigin("[P042][" + inputObject.getCardAcceptorIdentificationCode()+"]","Environment/Acceptor/id");
        mappingMetadata.addFieldOrigin("[P043][" + inputObject.getCardAcceptorNameLocation()+"]","Environment/Acceptor/nameAndLocation");
        mappingMetadata.addFieldOrigin("[P061][" + inputObject.getPosCardIssuer()+"]","Environment/Issuer/assigner");
        mappingMetadata.addFieldOrigin("[P003][" + inputObject.getProcessingCode()+"]","Transaction/AccountTo/accountFrom");
        mappingMetadata.addFieldOrigin("[P004][" + inputObject.getTransactionAmount()+"]","Transaction/TransactionAmounts/TransactionAmount/amount");
        mappingMetadata.addFieldOrigin("[P049][" + inputObject.getTransactionCurrencyCode()+"]","Transaction/TransactionAmounts/TransactionAmount/currency");
        mappingMetadata.addFieldOrigin("[P103][" + inputObject.getAccountIdentification()+"]","Transaction/AccountTo/accountId");
        mappingMetadata.addFieldOrigin("[P005][" + inputObject.getSettlementAmount()+"]","Transaction/TransactionAmounts/ReconciliationAmount/amount");
        mappingMetadata.addFieldOrigin("[P050][" + inputObject.getSettlementCurrencyCode()+"]","Transaction/TransactionAmounts/ReconciliationAmount/currency");
        mappingMetadata.addFieldOrigin("[P009][" + inputObject.getConversionRateSettlement()+"]","Transaction/TransactionAmounts/ReconciliationAmount/effectiveExchangeRate");
        mappingMetadata.addFieldOrigin("[P006][" + inputObject.getCardHolderBillingAmount()+"]","Transaction/TransactionAmounts/CardholderBillingAmount/amount");
        mappingMetadata.addFieldOrigin("[P051][" + inputObject.getCardholderBillingCurrencyCode()+"]","Transaction/TransactionAmounts/CardholderBillingAmount/currency");
        mappingMetadata.addFieldOrigin("[P010][" + inputObject.getConversionRate()+"]","Transaction/TransactionAmounts/CardholderBillingAmount/effectiveExchangeRate");
        mappingMetadata.addFieldOrigin("[P007][" + inputObject.getTransmissionDateTime()+"]","Transaction/TransactionId/transmissionDateTime");
        mappingMetadata.addFieldOrigin("[P011][" + inputObject.getSystemTraceAuditNumber()+"]","Transaction/TransactionId/systemTraceAuditNumber");
        mappingMetadata.addFieldOrigin("[P012][" + inputObject.getLocalTransactionDate()+"]","Transaction/TransactionId/localDate");
        mappingMetadata.addFieldOrigin("[P013][" + inputObject.getLocalTransactionTime()+"]","Transaction/TransactionId/localTime");
        mappingMetadata.addFieldOrigin("[P037][" + inputObject.getRetrievalReferenceNumber()+"]","Transaction/TransactionId/retrievalReferenceNumber");
        //mappingMetadata.addFieldOrigin("Transaction/TransactionAmounts/CardholderBillingAmount/effectiveExchangeRate", "[P054][" + inputObject.getConversionRate()+"]");
        mappingMetadata.addFieldOrigin("[P044][" + inputObject.getAdditionalResponseData()+"]","Transaction/AdditionalData/additionalResponseData");
        mappingMetadata.addFieldOrigin("[P025][" + inputObject.getPointServiceConditionCode()+"]","Transaction/messageReason");
        mappingMetadata.addFieldOrigin("[P015][" + inputObject.getSettlementDate()+"]","Context/TransactionContext/SettlementService/SettlementServiceDates/settlementDate");
        mappingMetadata.addFieldOrigin("[P018][" + inputObject.getMerchantType()+"]","Context/TransactionContext/merchantCategoryCode");
        mappingMetadata.addFieldOrigin("[P022][" + inputObject.getPointServiceEntryMode()+"]","Context/TransactionContext/pointOfServiceContext/cardDataEntryMode");
        mappingMetadata.addFieldOrigin("[P052][" + inputObject.getPinData()+"]","Context/Verification/VerificationInformation/value/PinData/encryptedPINBlock");
        mappingMetadata.addFieldOrigin("[P059][" + inputObject.getCampaignData()+"]","Context/saleContext/additionalData[campaignData]");
        mappingMetadata.addFieldOrigin("[P070][" + inputObject.getNetworkManagementInformationCode()+"]","supplementaryData[networkManagementInfoCode]");
        mappingMetadata.addFieldOrigin("[P120][" + inputObject.getKeyManagement()+"]","supplementaryData[keyManagement]");
        mappingMetadata.addFieldOrigin("[P125][" + inputObject.getSettlementData()+"]","supplementaryData[settlementData]");
        mappingMetadata.addFieldOrigin("[P126][" + inputObject.getIssuerTraceId()+"]","supplementaryData[issuerTraceId]");
        mappingMetadata.addFieldOrigin("[P016][" + inputObject.getDateConversion()+"]","supplementaryData[dateConversion]");
        mappingMetadata.addFieldOrigin("[P026][" + inputObject.getPointServicePIN()+"]","supplementaryData[pointServicePIN]");
        mappingMetadata.addFieldOrigin("[P056][" + inputObject.getPaymentAccountData()+"]","supplementaryData[paymentAccountData]");
        mappingMetadata.addFieldOrigin("[P094][" + inputObject.getServiceIndicator()+"]","supplementaryData[serviceIndicator]");
        mappingMetadata.addFieldOrigin("[P096][" + inputObject.getMessageSecurityCode()+"]","supplementaryData[messageSecurityCode]");
        mappingMetadata.addFieldOrigin("[P104][" + inputObject.getTransactionData()+"]","supplementaryData[transactionData]");
        mappingMetadata.addFieldOrigin("[P112][" + inputObject.getAdditionalDataNationalUse()+"]","supplementaryData[additionalDataNationalUse]");
        mappingMetadata.addFieldOrigin("[P121][" + inputObject.getAuthorizingAgentIdCode()+"]","supplementaryData[authorizingAgentIdCode]");
        mappingMetadata.addFieldOrigin("[P008][" + inputObject.getAmountCardholderBillingFee()+"]","supplementaryData[amountCardholderBillingFee]");
        mappingMetadata.addFieldOrigin("[P020][" + inputObject.getPrimaryAccountNumberCountryCode()+"]","supplementaryData[primaryAccountNumberCountryCode]");
        mappingMetadata.addFieldOrigin("[P021][" + inputObject.getForwardingInstitutionCountryCode()+"]","supplementaryData[forwardingInstitutionCountryCode]");
        mappingMetadata.addFieldOrigin("[P024][" + inputObject.getNetworkInternationalId()+"]","supplementaryData[networkInternationalId]");
        mappingMetadata.addFieldOrigin("[P027][" + inputObject.getAuthorizationIdResponseLength()+"]","supplementaryData[authorizationIdResponseLength]");
        mappingMetadata.addFieldOrigin("[P029][" + inputObject.getAmountSettlementFee()+"]","supplementaryData[amountSettlementFee]");
        mappingMetadata.addFieldOrigin("[P030][" + inputObject.getAmountTransactionProcessingFee()+"]","supplementaryData[amountTransactionProcessingFee]");
        mappingMetadata.addFieldOrigin("[P031][" + inputObject.getAmountSettlementProcessingFee()+"]","supplementaryData[amountSettlementProcessingFee]");
        mappingMetadata.addFieldOrigin("[P034][" + inputObject.getPrimaryAccountNumberExtended()+"]","supplementaryData[primaryAccountNumberExtended]");
        mappingMetadata.addFieldOrigin("[P036][" + inputObject.getTrackThreeData()+"]","supplementaryData[trackThreeData]");
        mappingMetadata.addFieldOrigin("[P046][" + inputObject.getExpandedAdditionalAmounts()+"]","supplementaryData[expandedAdditionalAmounts]");
        mappingMetadata.addFieldOrigin("[P047][" + inputObject.getAdditionalDataNationalUse2()+"]","supplementaryData[additionalDataNationalUse2]");
        mappingMetadata.addFieldOrigin("[P064][" + inputObject.getMessageAuthenticationCode()+"]","supplementaryData[messageAuthenticationCode]");
        mappingMetadata.addFieldOrigin("[P066][" + inputObject.getSettlementCode()+"]","supplementaryData[settlementCode]");
        mappingMetadata.addFieldOrigin("[P067][" + inputObject.getExtendedPaymentCode()+"]","supplementaryData[extendedPaymentCode]");
        mappingMetadata.addFieldOrigin("[P068][" + inputObject.getReceivingInstitutionCountryCode()+"]","supplementaryData[receivingInstitutionCountryCode]");
        mappingMetadata.addFieldOrigin("[P069][" + inputObject.getSettlementInstitutionCountryCode()+"]","supplementaryData[settlementInstitutionCountryCode]");
        mappingMetadata.addFieldOrigin("[P071][" + inputObject.getMessageNumber()+"]","supplementaryData[messageNumber]");
        mappingMetadata.addFieldOrigin("[P072][" + inputObject.getMessageNumberLast()+"]","supplementaryData[messageNumberLast]");
        mappingMetadata.addFieldOrigin("[P073][" + inputObject.getDateAction()+"]","supplementaryData[dateAction]");
        mappingMetadata.addFieldOrigin("[P074][" + inputObject.getCreditsNumber()+"]","supplementaryData[creditsNumber]");
        mappingMetadata.addFieldOrigin("[P075][" + inputObject.getCreditsReversalNumber()+"]","supplementaryData[creditsReversalNumber]");
        mappingMetadata.addFieldOrigin("[P076][" + inputObject.getDebitsNumber()+"]","supplementaryData[debitsNumber]");
        mappingMetadata.addFieldOrigin("[P077][" + inputObject.getDebitsReversalNumber()+"]","supplementaryData[debitsReversalNumber]");
        mappingMetadata.addFieldOrigin("[P078][" + inputObject.getTransferNumber()+"]","supplementaryData[transferNumber]");
        mappingMetadata.addFieldOrigin("[P079][" + inputObject.getTransferReversalNumber()+"]","supplementaryData[transferReversalNumber]");
        mappingMetadata.addFieldOrigin("[P080][" + inputObject.getInquiriesNumber()+"]","supplementaryData[inquiriesNumber]");
        mappingMetadata.addFieldOrigin("[P081][" + inputObject.getAuthorizationNumber()+"]","supplementaryData[authorizationNumber]");
        mappingMetadata.addFieldOrigin("[P082][" + inputObject.getCreditsProcessingFeeAmount()+"]","supplementaryData[creditsProcessingFeeAmount]");
        mappingMetadata.addFieldOrigin("[P083][" + inputObject.getCreditsTransactionFeeAmount()+"]","supplementaryData[creditsTransactionFeeAmount]");
        mappingMetadata.addFieldOrigin("[P084][" + inputObject.getDebitsProcessingFeeAmount()+"]","supplementaryData[debitsProcessingFeeAmount]");
        mappingMetadata.addFieldOrigin("[P085][" + inputObject.getDebitsTransactionFeeAmount()+"]","supplementaryData[debitsTransactionFeeAmount]");
        mappingMetadata.addFieldOrigin("[P086][" + inputObject.getCreditsAmount()+"]","supplementaryData[creditsAmount]");
        mappingMetadata.addFieldOrigin("[P087][" + inputObject.getCreditsReversalAmount()+"]","supplementaryData[creditsReversalAmount]");
        mappingMetadata.addFieldOrigin("[P088][" + inputObject.getDebitsAmount()+"]","supplementaryData[debitsAmount]");
        mappingMetadata.addFieldOrigin("[P089][" + inputObject.getDebitsReversalAmount()+"]","supplementaryData[debitsReversalAmount]");
        mappingMetadata.addFieldOrigin("[P091][" + inputObject.getIssuerFileUpdateCode()+"]","supplementaryData[issuerFileUpdateCode]");
        mappingMetadata.addFieldOrigin("[P092][" + inputObject.getFileSecurityCode()+"]","supplementaryData[fileSecurityCode]");
        mappingMetadata.addFieldOrigin("[P093][" + inputObject.getResponseIndicator()+"]","supplementaryData[responseIndicator]");
        mappingMetadata.addFieldOrigin("[P095][" + inputObject.getReplacementAmounts()+"]","supplementaryData[replacementAmounts]");
        mappingMetadata.addFieldOrigin("[P097][" + inputObject.getAmountNetSettlement()+"]","supplementaryData[amountNetSettlement]");
        mappingMetadata.addFieldOrigin("[P098][" + inputObject.getPayee()+"]","supplementaryData[payee]");
        mappingMetadata.addFieldOrigin("[P099][" + inputObject.getSettlementInstitutionIdentificationCode()+"]","supplementaryData[settlementInstitutionIdentificationCode]");
        mappingMetadata.addFieldOrigin("[P100][" + inputObject.getReceivingInstitutionIdentificationCode()+"]","supplementaryData[receivingInstitutionIdentificationCode]");
        mappingMetadata.addFieldOrigin("[P101][" + inputObject.getFileName()+"]","supplementaryData[fileName]");
        mappingMetadata.addFieldOrigin("[P102][" + inputObject.getAccountIdentification1()+"]","supplementaryData[accountIdentification1]");
        mappingMetadata.addFieldOrigin("[P106][" + inputObject.getFleetServiceData()+"]","supplementaryData[fleetServiceData]");
        mappingMetadata.addFieldOrigin("[P108][" + inputObject.getAdditionalTransactionReferenceData()+"]","supplementaryData[additionalTransactionReferenceData]");
        mappingMetadata.addFieldOrigin("[P109][" + inputObject.getIsoUse()+"]","supplementaryData[isoUse]");
        mappingMetadata.addFieldOrigin("[P115][" + inputObject.getReservedNationalUse()+"]","supplementaryData[reservedNationalUse]");
        mappingMetadata.addFieldOrigin("[P119][" + inputObject.getReservedNationalUse2()+"]","supplementaryData[reservedNationalUse2]");
        mappingMetadata.addFieldOrigin("[P127][" + inputObject.getPrivateData()+"]","supplementaryData[privateData]");
        mappingMetadata.addFieldOrigin("[P128][" + inputObject.getMessageAuthenticationCode2()+"]","supplementaryData[messageAuthenticationCode2]");
        mappingMetadata.addFieldOrigin("[P055][" + inputObject.getIntegratedCircuitCard()+"]","iccRelatedData");
        return mappingMetadata;
    }

}
